Repository hedgedoc/react-client, pull requests merged in 2020-05, with the labels that each got.

#77 started issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question---other.md
Labels: enhancement

#80 Add version info
  public/backend-config.json
  public/locales/en.json
  src/components/landing/layout/footer/powered-by-links.tsx
  src/components/landing/layout/footer/social-links.tsx
  src/components/landing/layout/footer/translated-link.tsx
  src/components/landing/layout/version-info/version-info.tsx
  src/components/landing/layout/version-info/version-input-field.tsx
  src/components/links/external-link.tsx
  src/components/links/translated-external-link.tsx
  src/initializers/fontAwesome.ts
  src/redux/backend-config/reducers.ts
  src/redux/backend-config/types.ts
  src/version.json
Labels: feature, intro

#82 added clearHistory functionality
  public/locales/en.json
  src/components/landing/pages/history/history-content/history-content.tsx
  src/components/landing/pages/history/history-toolbar/clear-history-button.tsx
  src/components/landing/pages/history/history-toolbar/history-toolbar.tsx
  src/components/landing/pages/history/history.tsx
  src/utils/historyUtils.ts
Labels: feature, history

#84 Feature/history api
  src/api/config.ts
  src/api/default.ts
  src/api/history.ts
  src/api/user.ts
  src/components/landing/pages/login/auth/via-email.tsx
  src/components/landing/pages/login/auth/via-ldap.tsx
  src/components/landing/pages/login/auth/via-openid.tsx
  src/redux/frontend-config/methods.ts
Labels: feature, history

#86 Fix dark mode button
  src/components/editor/task-bar/dark-mode-button.tsx
Labels: editor, enhancement

#87 better error messages for the loading-screen
  public/api/v2.0/config
  src/api/config.ts
  src/components/application-loader/application-loader.tsx
  src/components/application-loader/loading-screen.tsx
  src/initializers/i18n.ts
  src/initializers/index.ts
Labels: enhancement

#97 Make application loader only trigger once
  src/components/application-loader/application-loader.tsx
Labels: bug

#94 New locale format
  public/locales/ar.json
  public/locales/ca.json
  public/locales/cs.json
  public/locales/da.json
  public/locales/de.json
  public/locales/el.json
  public/locales/en.json
  public/locales/eo.json
  public/locales/es.json
  public/locales/fr.json
  public/locales/hi.json
  public/locales/hr.json
  public/locales/id.json
  public/locales/it.json
  public/locales/ja.json
  public/locales/ko.json
  public/locales/nl.json
  public/locales/pl.json
  public/locales/pt.json
  public/locales/ru.json
  public/locales/sk.json
  public/locales/sr.json
  public/locales/sv.json
  public/locales/tr.json
  public/locales/uk.json
  public/locales/vi.json
  public/locales/zh-CN.json
  public/locales/zh-TW.json
  src/components/application-loader/application-loader.tsx
  src/components/editor/task-bar/dark-mode-button.tsx
  src/components/editor/task-bar/editor-menu.tsx
  src/components/editor/task-bar/editor-view-mode.tsx
  src/components/editor/task-bar/task-bar.tsx
  src/components/landing/layout/footer/powered-by-links.tsx
  src/components/landing/layout/footer/social-links.tsx
  src/components/landing/layout/navigation/header-bar/header-bar.tsx
  src/components/landing/layout/navigation/new-guest-note-button.tsx
  src/components/landing/layout/navigation/new-user-note-button.tsx
  src/components/landing/layout/navigation/sign-in-button.tsx
  src/components/landing/layout/navigation/user-dropdown/user-dropdown.tsx
  src/components/landing/layout/user-avatar/user-avatar.tsx
  src/components/landing/layout/version-info/version-info.tsx
  src/components/landing/layout/version-info/version-input-field.tsx
  src/components/landing/pages/history/history-card/history-card.tsx
  src/components/landing/pages/history/history-content/history-content.tsx
  src/components/landing/pages/history/history-table/history-table-row.tsx
  src/components/landing/pages/history/history-table/history-table.tsx
  src/components/landing/pages/history/history-toolbar/clear-history-button.tsx
  src/components/landing/pages/history/history-toolbar/history-toolbar.tsx
  src/components/landing/pages/history/history.tsx
  src/components/landing/pages/intro/cover-buttons/cover-buttons.tsx
  src/components/landing/pages/intro/feature-links.tsx
  src/components/landing/pages/intro/intro.tsx
  src/components/landing/pages/login/auth/via-email.tsx
  src/components/landing/pages/login/auth/via-ldap.tsx
  src/components/landing/pages/login/auth/via-openid.tsx
  src/components/landing/pages/login/login.tsx
Labels: enhancement

#95 Make eslint packages not dev only
  package.json
Labels: enhancement

#106 Restructure Link Components and fix internal link children error
  src/components/application-loader/loading-screen.tsx
  src/components/landing/layout/footer/powered-by-links.tsx
  src/components/links/external-link.tsx
  src/components/links/internal-link.tsx
  src/components/links/translated-external-link.tsx
  src/components/links/translated-internal-link.tsx
  src/components/links/types.ts
Labels: bug

#108 change dark mode button to show sun icon if toggled
  src/components/editor/task-bar/dark-mode-button.tsx
  src/initializers/fontAwesome.ts
Labels: editor, enhancement

#107 Fixed wrong translation at versionInfo label
  src/components/landing/layout/version-info/version-info.tsx
Labels: bug

#110 Add flex to grow button
  src/components/landing/layout/navigation/header-bar/header-bar.tsx
Labels: bug

#111 Replace react icon with default codimd icon
  icon/icon.svg
  public/favicon.ico
  public/icons/android-chrome-192x192.png
  public/icons/android-chrome-512x512.png
  public/icons/apple-touch-icon.png
  public/icons/browserconfig.xml
  public/icons/favicon-16x16.png
  public/icons/favicon-32x32.png
  public/icons/favicon.ico
  public/icons/mstile-144x144.png
  public/icons/mstile-150x150.png
  public/icons/mstile-310x150.png
  public/icons/mstile-310x310.png
  public/icons/mstile-70x70.png
  public/icons/safari-pinned-tab.svg
  public/icons/site.webmanifest
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
Labels: enhancement

#113 Split user.ts into auth.ts and me.ts
  src/api/auth.ts
  src/api/me.ts
  src/components/landing/pages/login/auth/via-email.tsx
  src/components/landing/pages/login/auth/via-ldap.tsx
  src/components/landing/pages/login/auth/via-openid.tsx
  src/components/landing/pages/profile/settings/profile-account-management.tsx
  src/components/landing/pages/profile/settings/profile-change-password.tsx
  src/components/landing/pages/profile/settings/profile-display-name.tsx
  src/utils/apiUtils.ts
Labels: enhancement

#109 Restructure redux code
  src/api/backend-config/index.ts
  src/api/backend-config/types.ts
  src/api/config.ts
  src/api/frontend-config/index.ts
  src/api/frontend-config/types.ts
  src/components/editor/editor.tsx
  src/components/editor/task-bar/editor-view-mode.tsx
  src/components/landing/layout/navigation/header-bar/header-bar.tsx
  src/components/landing/layout/navigation/user-dropdown/user-dropdown.tsx
  src/components/landing/pages/intro/cover-buttons/cover-buttons.tsx
  src/components/landing/pages/login/login.tsx
  src/components/landing/pages/profile/profile.tsx
  src/components/landing/pages/profile/settings/profile-display-name.tsx
  src/initializers/configLoader.ts
  src/redux/backend-config/methods.ts
  src/redux/backend-config/reducers.ts
  src/redux/backend-config/types.ts
  src/redux/editor/methods.ts
  src/redux/editor/reducers.ts
  src/redux/editor/types.ts
  src/redux/frontend-config/methods.ts
  src/redux/frontend-config/reducers.ts
  src/redux/frontend-config/types.ts
  src/redux/index.ts
  src/redux/user/methods.ts
  src/redux/user/reducers.ts
  src/redux/user/types.ts
  src/utils/apiUtils.ts
Labels: enhancement

#116 Fix text color when hovering social link buttons
  src/components/landing/pages/login/auth/social-link-button/social-link-button.scss
Labels: bug
