Repository hedgedoc/react-client, pull requests merged in 2020-10, with the labels that each got.

#621 replaces moment with luxon
  package.json
  src/components/application-loader/initializers/i18n.ts
  src/components/editor/document-bar/document-info/document-info-button.tsx
  src/components/editor/document-bar/document-info/document-info-time-line.tsx
  src/components/editor/document-bar/document-info/time-from-now.tsx
  src/components/editor/document-bar/revisions/revision-modal-list-entry.tsx
  src/components/editor/editor-pane/autocompletion/link-and-extra-tag.ts
  src/components/history-page/history-card/history-card.tsx
  src/components/history-page/history-page.tsx
  src/components/history-page/utils.ts
  src/components/landing-layout/footer/language-picker.tsx
  yarn.lock
Labels: code quality, ready to merge

#628 Add common download helper
  src/components/common/download/download.ts
  src/components/editor/document-bar/revisions/utils.ts
  src/components/history-page/history-page.tsx
  src/components/history-page/utils.ts
Labels: code quality, ready to merge

#644 fixed help modal width
  src/components/editor/app-bar/help-button/help-button.tsx
Labels: editor, enhancement, ready to merge

#627 added markdown export
  cypress/integration/export.spec.ts
  src/components/common/download/download.ts
  src/components/editor/document-bar/document-bar.tsx
  src/components/editor/document-bar/menus/export-menu.tsx
  src/components/editor/document-bar/menus/export/markdown.tsx
Labels: editor, feature, ready to merge

#646 added js as an extra highlighted language
  src/components/editor/editor-pane/autocompletion/code-block.ts
  src/components/editor/editorTestContent.ts
  src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-code/highlighted-code.tsx
Labels: ready to merge, renderer

#654 Enforce no warnings during linting
  package.json
Labels: code quality

#655 Markmap make mouse input toggle
  public/locales/en.json
  src/components/common/lock-button/lock-button.tsx
  src/components/markdown-renderer/replace-components/markmap/markmap-frame.tsx
Labels: enhancement, ready to merge, renderer

#645 Added markdown-file import
  CHANGELOG.md
  cypress/fixtures/import.md
  cypress/integration/import.spec.ts
  cypress/support/index.ts
  package.json
  public/locales/en.json
  src/components/editor/document-bar/document-bar.tsx
  src/components/editor/document-bar/import/import-file.tsx
  src/components/editor/document-bar/menus/import-menu.tsx
  src/components/editor/editor.tsx
  yarn.lock
Labels: editor, feature, ready to merge

#653 Add access token management to profile
  CHANGELOG.md
  cypress/integration/profile.spec.ts
  public/api/v2/tokens
  public/locales/en.json
  src/api/tokens/index.ts
  src/api/tokens/types.d.ts
  src/components/common/icon-button/icon-button.tsx
  src/components/profile-page/access-tokens/profile-access-tokens.tsx
  src/components/profile-page/profile-page.tsx
Labels: feature, profile page, ready to merge

#663 added missing button-inside css file in MarkmapFrame
  src/components/markdown-renderer/replace-components/markmap/markmap-frame.tsx
Labels: bug, ready to merge, renderer

#620 Replace emoji-mart with emoji-picker-element
  CHANGELOG.md
  craco.config.js
  cypress/integration/autocompletion.spec.ts
  cypress/integration/toolbar.spec.ts
  package.json
  src/components/editor/editor-pane/autocompletion/emoji.ts
  src/components/editor/editor-pane/tool-bar/emoji-picker/emoji-picker-button.tsx
  src/components/editor/editor-pane/tool-bar/emoji-picker/emoji-picker.scss
  src/components/editor/editor-pane/tool-bar/emoji-picker/emoji-picker.tsx
  src/components/editor/editor-pane/tool-bar/utils/emojiUtils.ts
  src/components/editor/editor-pane/tool-bar/utils/toolbarButtonUtils.test.ts
  src/components/editor/editor-pane/tool-bar/utils/toolbarButtonUtils.ts
  src/components/markdown-renderer/markdown-it-plugins/emoji/mapping.ts
  src/external-types/emoji-mart/dist-es/utils/emoji-index/nimble-emoji-index.d.ts
  yarn.lock
Labels: editor, enhancement, ready to merge

#668 Activate markdown folding
  src/components/editor/editor-pane/editor-pane.scss
  src/components/editor/editor-pane/editor-pane.tsx
Labels: editor, enhancement, ready to merge

#664 Updates twemoji.ttf with a new version that is built for twemoji 13
  src/components/editor/editor-pane/editor-pane.scss
  src/components/editor/editor-pane/tool-bar/emoji-picker/emoji-picker.tsx
  src/components/markdown-renderer/markdown-renderer.scss
  src/components/markdown-renderer/replace-components/flow/flowchart/flowchart.tsx
  src/style/fonts/twemoji/TwemojiMozilla.ttf
  src/style/fonts/twemoji/twemoji.scss
  src/style/index.scss
Labels: enhancement, ready to merge

#671 updated flowchart.js
  package.json
  src/external-types/flowchart.js/index.d.ts
  yarn.lock
Labels: code quality, ready to merge

#563 Add read-only view (/s/note)
  CHANGELOG.md
  public/api/v2/notes/banner
  public/api/v2/notes/old
  public/locales/en.json
  src/api/notes/index.ts
  src/components/common/document-title/note-title-extractor.ts
  src/components/common/links/external-link.tsx
  src/components/common/links/internal-link.tsx
  src/components/common/links/types.d.ts
  src/components/common/user-avatar/user-avatar.scss
  src/components/common/user-avatar/user-avatar.tsx
  src/components/editor/app-bar/app-bar.tsx
  src/components/editor/document-bar/document-info/document-info-button.tsx
  src/components/editor/document-bar/document-info/document-info-line.tsx
  src/components/editor/document-bar/document-info/document-info-time-line.scss
  src/components/editor/document-bar/document-info/document-info-time-line.tsx
  src/components/editor/document-renderer-pane/document-render-pane.tsx
  src/components/editor/document-renderer-pane/scrolling-document-render-pane.tsx
  src/components/editor/editor.tsx
  src/components/pad-view-only/document-infobar.scss
  src/components/pad-view-only/document-infobar.tsx
  src/components/pad-view-only/pad-view-only.tsx
  src/index.tsx
Labels: feature

#666 Replace empty components with hooks
  src/components/editor/editor.tsx
  src/components/landing-layout/landing-layout.tsx
  src/components/pad-view-only/pad-view-only.tsx
  src/hooks/common/use-apply-dark-mode.ts
  src/hooks/common/use-document-title.ts
Labels: code quality

#667 Set background or alternative colors for diagrams
  src/components/markdown-renderer/markdown-renderer.scss
  src/components/markdown-renderer/replace-components/flow/flowchart/flowchart.tsx
  src/components/markdown-renderer/replace-components/mermaid/mermaid-chart.tsx
  src/components/markdown-renderer/replace-components/mermaid/mermaid.scss
  src/external-types/flowchart.js/index.d.ts
Labels: enhancement

#719 Update multiple packages
  cypress/.eslintrc.json
  cypress/integration/import.spec.ts
  package.json
  src/components/common/branding/branding.tsx
  src/components/common/icon-button/translated-icon-button.tsx
  src/components/editor/document-bar/revisions/revision-modal-list-entry.tsx
  src/components/editor/editor-pane/key-map.ts
  src/components/editor/editor-pane/tool-bar/utils/toolbarButtonUtils.test.disabled.ts
  src/components/editor/editor-pane/tool-bar/utils/toolbarButtonUtils.test.ts
  src/components/editor/yaml-metadata/yaml-metadata.ts
  src/components/history-page/history-content/history-content.tsx
  src/components/history-page/sort-button/sort-button.tsx
  src/components/landing-layout/navigation/header-bar/header-bar.tsx
  src/components/markdown-renderer/markdown-it-configurator/FullMarkdownItConfigurator.tsx
  src/components/markdown-renderer/replace-components/mermaid/mermaid-chart.tsx
  src/external-types/markdown-it-mathjax/index.d.ts
  src/index.tsx
  src/service-worker-registration.ts
  src/service-worker.ts
  tsconfig.json
  yarn.lock
Labels: dependencies

#699 Use bare version of markdown-it-emoji
  src/components/markdown-renderer/markdown-it-plugins/twitter-emojis.ts
  src/external-types/markdown-it-emoji/index.d.ts
Labels: enhancement, renderer

#698 Fix font-color in flowchart
  src/components/markdown-renderer/replace-components/flow/flowchart/flowchart.tsx
Labels: bug, renderer

#696 Disable check box if no onTaskCheckedChange is provided
  src/components/markdown-renderer/full-markdown-renderer.tsx
  src/components/markdown-renderer/hooks/use-replacer-instance-list-creator.ts
  src/components/markdown-renderer/replace-components/task-list/task-list-replacer.tsx
Labels: enhancement

#694 Use editor-preference-select for spell check
  public/locales/en.json
  src/components/editor/editor-pane/tool-bar/editor-preferences/editor-preference-select.tsx
  src/components/editor/editor-pane/tool-bar/editor-preferences/editor-preferences.tsx
Labels: code quality, editor, enhancement

#689 extract code into useFirstDraw hook
  src/components/editor/editor.tsx
  src/components/editor/hooks/useFirstDraw.ts
Labels: code quality

#688 Extract view mode shortcut code into hook
  src/components/editor/editor.tsx
  src/components/editor/hooks/useViewModeShortcuts.ts
Labels: code quality

#692 extract scroll code from renderer into hook
  src/components/editor/document-renderer-pane/scrolling-document-render-pane.tsx
  src/components/editor/scroll/hooks/use-scroll-to-line-mark.ts
  src/components/editor/scroll/hooks/use-user-scroll.ts
Labels: code quality, enhancement

#691 Improvement/move document content into redux
  src/components/editor/document-bar/document-bar.tsx
  src/components/editor/document-bar/import/import-file.tsx
  src/components/editor/document-bar/menus/export-menu.tsx
  src/components/editor/document-bar/menus/export/markdown.tsx
  src/components/editor/document-bar/menus/import-menu.tsx
  src/components/editor/document-bar/revisions/revision-button.tsx
  src/components/editor/document-bar/revisions/revision-modal.tsx
  src/components/editor/document-renderer-pane/document-render-pane.tsx
  src/components/editor/document-renderer-pane/scrolling-document-render-pane.tsx
  src/components/editor/editor.tsx
  src/components/pad-view-only/pad-view-only.tsx
  src/redux/document-content/methods.ts
  src/redux/document-content/reducers.ts
  src/redux/document-content/types.ts
  src/redux/index.ts
Labels: code quality, enhancement, ready to merge

#673 Removed 'ago'-suffix from translations
  public/locales/en.json
Labels: bug, ready to merge

#736 moved alertContainer to basic renderer from full renderer
  src/components/editor/app-bar/help-button/cheatsheet.tsx
  src/components/markdown-renderer/markdown-it-configurator/BasicMarkdownItConfigurator.tsx
  src/components/markdown-renderer/markdown-it-configurator/FullMarkdownItConfigurator.tsx
Labels: ready to merge
