Repository hedgedoc/react-client, pull requests merged in 2020-11, with the labels that each got.

#725 move taskLists from full to basic renderer
  cypress/integration/code.spec.ts
  cypress/integration/helpDialog.spec.ts
  src/components/markdown-renderer/markdown-it-configurator/BasicMarkdownItConfigurator.tsx
  src/components/markdown-renderer/markdown-it-configurator/FullMarkdownItConfigurator.tsx
Labels: ready to merge

#720 Refactor emoji code
  package.json
  src/components/editor/editor-pane/autocompletion/emoji.ts
  src/components/editor/editor-pane/tool-bar/emoji-picker/emoji-picker.tsx
  yarn.lock
Labels: code quality, editor

#756 added screenshots artifacts in e2e workflow
  .github/workflows/e2e.yml
Labels: ready to merge

#606 Feature/hedgedoc logo
  cypress/integration/intro.spec.ts
  public/icons/android-chrome-192x192.png
  public/icons/android-chrome-512x512.png
  public/icons/apple-touch-icon.png
  public/icons/browserconfig.xml
  public/icons/favicon-16x16.png
  public/icons/favicon-32x32.png
  public/icons/favicon.ico
  public/icons/mstile-144x144.png
  public/icons/mstile-150x150.png
  public/icons/mstile-310x150.png
  public/icons/mstile-310x310.png
  public/icons/mstile-70x70.png
  public/icons/safari-pinned-tab.svg
  public/icons/site.webmanifest
  public/index.html
  src/components/application-loader/application-loader.scss
  src/components/application-loader/loading-screen.tsx
  src/components/common/branding/branding.tsx
  src/components/common/hedge-doc-logo/hedge-doc-logo-with-text.tsx
  src/components/common/hedge-doc-logo/hedge-doc-logo.tsx
  src/components/common/hedge-doc-logo/logo_color.svg
  src/components/common/hedge-doc-logo/logo_text_bw_horizontal.svg
  src/components/common/hedge-doc-logo/logo_text_color_vertical.svg
  src/components/common/hedge-doc-logo/logo_text_wb_horizontal.svg
  src/components/editor/app-bar/navbar-branding.tsx
  src/components/intro-page/intro-page.tsx
Labels: feature, ready to merge

#781 added gitSignOff preset to renovate
  renovate.json
Labels: ready to merge

#799 added copy check in the code e2e test
  cypress/integration/code.spec.ts
  cypress/plugins/index.js
Labels: ready to merge

#804 Fixed branding icon path in mocked cypress config
  cypress/support/config.ts
Labels: bug

#803 Use safer node_modules cache
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .github/workflows/lint.yml
Labels: ready to merge

#763 added table overlay to table toolbar button.
  CHANGELOG.md
  cypress/integration/toolbar.spec.ts
  public/locales/en.json
  src/components/common/number-range/number-range.ts
  src/components/editor/editor-pane/tool-bar/table-picker/custom-table-size-modal.tsx
  src/components/editor/editor-pane/tool-bar/table-picker/table-picker-button.tsx
  src/components/editor/editor-pane/tool-bar/table-picker/table-picker.scss
  src/components/editor/editor-pane/tool-bar/table-picker/table-picker.tsx
  src/components/editor/editor-pane/tool-bar/tool-bar.tsx
  src/components/editor/editor-pane/tool-bar/utils/toolbarButtonUtils.ts
Labels: ready to merge

#808 Extract windows location code into hook
  src/components/application-loader/application-loader.tsx
  src/hooks/common/use-frontend-base-url.ts
Labels: code quality
