Repository hedgedoc/react-client, pull requests merged in 2020-12, with the labels that each got.

#807 Ignore .eslintcache
  .gitignore
Labels: status: ready to merge, type: code quality enhancement

#810 Remove OFL-1.1-RFN.txt
  LICENSES/OFL-1.1-RFN.txt
Labels: status: ready to merge, type: documentation

#833 Add new package group for markmap
  renovate.json
Labels: priority: 1 high, type: maintenance

#809 Add custom language list for highlight js without 1c
  CHANGELOG.md
  LICENSES/BSD-3-Clause.txt
  cypress/integration/autocompletion.spec.ts
  src/components/common/hljs/hljs.ts
  src/components/editor/editor-pane/autocompletion/code-block.ts
  src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-code/highlighted-code.tsx
  src/external-types/highlight.js/core.d.ts
Labels: status: ready to merge, type: feature enhancement

#834 Update and optimize markmap
  package.json
  src/components/markdown-renderer/replace-components/markmap/markmap-frame.tsx
  src/components/markdown-renderer/replace-components/markmap/markmap-loader.ts
  yarn.lock
Labels: type: feature enhancement, type: maintenance

#854 Change tsconfig for jsx transpiler
  tsconfig.json
Labels: type: code quality enhancement

#856 Add jetbrains copyright autocomplection
  .gitignore
  .idea/copyright/hedgedoc.xml
  .idea/copyright/profiles_settings.xml
  .reuse/dep5
Labels: type: code quality enhancement

#695 Use fira code in editor
  CHANGELOG.md
  package.json
  public/locales/en.json
  src/components/editor/editor-pane/editor-pane.scss
  src/components/editor/editor-pane/editor-pane.tsx
  src/components/editor/editor-pane/tool-bar/editor-preferences/editor-preference-boolean-property.tsx
  src/components/editor/editor-pane/tool-bar/editor-preferences/editor-preference-input.tsx
  src/components/editor/editor-pane/tool-bar/editor-preferences/editor-preference-ligatures-select.tsx
  src/components/editor/editor-pane/tool-bar/editor-preferences/editor-preference-number-property.tsx
  src/components/editor/editor-pane/tool-bar/editor-preferences/editor-preference-property.ts
  src/components/editor/editor-pane/tool-bar/editor-preferences/editor-preference-select-property.tsx
  src/components/editor/editor-pane/tool-bar/editor-preferences/editor-preference-select.tsx
  src/components/editor/editor-pane/tool-bar/editor-preferences/editor-preferences.tsx
  src/components/markdown-renderer/replace-components/flow/flowchart/flowchart.tsx
  src/redux/editor/methods.ts
  src/redux/editor/reducers.ts
  src/redux/editor/types.ts
  src/style/index.scss
  yarn.lock
Labels: scope: editor, type: feature enhancement

#758 added upload functionality
  cypress/fixtures/acme.png
  cypress/fixtures/acme.png.license
  cypress/integration/intro.spec.ts
  cypress/integration/upload.spec.ts
  public/locales/de.json
  public/locales/en.json
  src/api/media/index.ts
  src/components/common/hidden-input-menu-entry/hidden-input-menu-entry.tsx
  src/components/editor/document-bar/import/import-file.tsx
  src/components/editor/document-bar/menus/import-menu.tsx
  src/components/editor/editor-pane/editor-pane.scss
  src/components/editor/editor-pane/editor-pane.tsx
  src/components/editor/editor-pane/tool-bar/tool-bar.tsx
  src/components/editor/editor-pane/tool-bar/utils/upload-image-mimetypes.ts
  src/components/editor/editor-pane/upload-handler.ts
  src/components/editor/editor.tsx
  src/redux/document-content/methods.ts
  src/redux/document-content/reducers.ts
  src/redux/document-content/types.ts
  yarn.lock
Labels: scope: editor, type: feature

#859 Fix bug that pathname is always empty
  src/hooks/common/use-frontend-base-url.ts
Labels: type: bug

#875 Replace codimd with hedgedoc
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  cypress/integration/documentTitle.spec.ts
  cypress/integration/link.spec.ts
  cypress/integration/toolbar.spec.ts
  public/api/v2/notes/features/revisions/1598389571
  public/api/v2/notes/features/revisions/1598390307
  src/links.json
Labels: priority: 0 critical, status: confirmed, type: documentation

#860 Enhance share dialog
  CHANGELOG.md
  public/locales/en.json
  src/components/common/copyable/copyable-field/copyable-field.tsx
  src/components/editor/app-bar/editor-view-mode.tsx
  src/components/editor/document-bar/buttons/share-link-button.tsx
  src/components/editor/editor.tsx
  src/components/pad-view-only/pad-view-only.tsx
  src/redux/document-content/methods.ts
  src/redux/document-content/reducers.ts
  src/redux/document-content/types.ts
Labels: scope: editor, status: ready to merge, type: feature enhancement

#873 Add support for editor-mode URL parameters
  cypress/integration/editorMode.spec.ts
  src/components/editor/app-bar/editor-view-mode.tsx
  src/components/editor/editor.tsx
Labels: scope: editor, status: ready to merge, type: feature

#877 Replace youtube link with a working one
  src/components/editor/editorTestContent.ts
Labels: priority: 3 low, scope: editor, status: confirmed, status: ready to merge, type: feature enhancement

#876 Remove first draw hook
  src/components/editor/editor.tsx
  src/components/editor/hooks/useFirstDraw.ts
Labels: priority: 2 medium, scope: editor, status: confirmed, status: ready to merge, type: code quality enhancement

#878 Improvement/update better task list
  package.json
  src/components/markdown-renderer/markdown-it-plugins/tasks-lists.ts
  src/components/markdown-renderer/replace-components/task-list/task-list-replacer.tsx
  yarn.lock
Labels: priority: 0 critical, scope: editor, scope: renderer, status: confirmed, type: maintenance

#892 update markdown-it-anchor
  package.json
  src/components/markdown-renderer/markdown-it-plugins/headline-anchors.ts
  yarn.lock
Labels: type: maintenance

#893 Regenerate yarn.lock
  package.json
  src/style/index.scss
  yarn.lock
Labels: type: maintenance

#897 Rename npm task
  package.json
Labels: priority: 3 low, type: code quality enhancement

#898 Add test mode
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  README.md
  package.json
  src/index.tsx
  src/utils/is-test-mode.ts
Labels: priority: 0 critical, type: code quality enhancement
