Repository hedgedoc/react-client, pull requests merged in 2021-12, with the labels that each got.

#1636 Refactor profile page
  cypress/integration/profile.spec.ts
  locales/en.json
  public/mock-backend/api/private/tokens
  src/api/tokens/index.ts
  src/api/tokens/types.d.ts
  src/components/common/countdown-button/countdown-button.tsx
  src/components/profile-page/access-tokens/access-token-created-modal.tsx
  src/components/profile-page/access-tokens/access-token-creation-form/access-token-creation-form-expiry-field.tsx
  src/components/profile-page/access-tokens/access-token-creation-form/access-token-creation-form-field.d.ts
  src/components/profile-page/access-tokens/access-token-creation-form/access-token-creation-form-label-field.tsx
  src/components/profile-page/access-tokens/access-token-creation-form/access-token-creation-form-submit-button.tsx
  src/components/profile-page/access-tokens/access-token-creation-form/access-token-creation-form.tsx
  src/components/profile-page/access-tokens/access-token-creation-form/hooks/use-expiry-dates.ts
  src/components/profile-page/access-tokens/access-token-creation-form/hooks/use-on-create-token.ts
  src/components/profile-page/access-tokens/access-token-deletion-modal.tsx
  src/components/profile-page/access-tokens/access-token-list-entry.tsx
  src/components/profile-page/access-tokens/profile-access-tokens.tsx
  src/components/profile-page/account-management/account-deletion-modal.tsx
  src/components/profile-page/account-management/profile-account-management.tsx
  src/components/profile-page/profile-page.tsx
  src/components/profile-page/settings/profile-account-management.tsx
  src/components/profile-page/settings/profile-change-password.tsx
  src/components/profile-page/settings/profile-display-name.tsx
Labels: type: code quality enhancement

#1663 Iframe capsule
  CHANGELOG.md
  cypress/integration/iframe-capsule.ts
  src/components/markdown-renderer/hooks/use-markdown-extensions.ts
  src/components/markdown-renderer/markdown-extension/iframe-capsule/iframe-capsule-markdown-extension.ts
  src/components/markdown-renderer/markdown-extension/iframe-capsule/iframe-capsule-replacer.tsx
  src/components/markdown-renderer/replace-components/click-shield/click-shield.scss
  src/components/markdown-renderer/replace-components/click-shield/click-shield.tsx
Labels: type: feature

#1664 Move frontmatter types
  src/components/editor-page/app-bar/app-bar.tsx
  src/components/editor-page/document-bar/share/share-modal.tsx
  src/components/editor-page/editor-page.tsx
  src/components/editor-page/renderer-pane/hooks/use-send-frontmatter-info-from-redux-to-renderer.ts
  src/components/markdown-renderer/hooks/use-reveal.ts
  src/components/markdown-renderer/slideshow-markdown-renderer.tsx
  src/components/render-page/iframe-markdown-renderer.tsx
  src/components/render-page/markdown-document.tsx
  src/components/render-page/window-post-message-communicator/rendering-message.ts
  src/redux/index.ts
  src/redux/note-details/frontmatter-extractor/extractor.test.ts
  src/redux/note-details/frontmatter-extractor/extractor.ts
  src/redux/note-details/frontmatter-extractor/types.d.ts
  src/redux/note-details/initial-state.ts
  src/redux/note-details/raw-note-frontmatter-parser/parser.test.ts
  src/redux/note-details/raw-note-frontmatter-parser/parser.ts
  src/redux/note-details/raw-note-frontmatter-parser/types.d.ts
  src/redux/note-details/reducer.ts
  src/redux/note-details/types.ts
  src/redux/note-details/types/iso6391.ts
  src/redux/note-details/types/note-details.ts
  src/redux/note-details/types/slide-show-options.d.ts
Labels: type: code quality enhancement

#1662 Refactor table size picker
  cypress/integration/toolbar.spec.ts
  locales/en.json
  src/components/editor-page/editor-pane/tool-bar/table-picker/custom-table-size-modal.tsx
  src/components/editor-page/editor-pane/tool-bar/table-picker/table-picker-button.tsx
  src/components/editor-page/editor-pane/tool-bar/table-picker/table-picker.scss
  src/components/editor-page/editor-pane/tool-bar/table-picker/table-picker.tsx
  src/components/editor-page/editor-pane/tool-bar/table-picker/table-size-picker-popover.tsx
  src/components/editor-page/editor-pane/tool-bar/table-picker/table-size-text.tsx
  src/components/markdown-renderer/hooks/use-on-ref-change.ts
Labels: type: code quality enhancement

#1677 Remove console.log
  src/components/editor-page/editor-pane/status-bar/selection-info.tsx
Labels: type: code quality enhancement

#1678 Refactor login components and adjust login API routes
  cypress/integration/signInButton.spec.ts
  cypress/support/config.ts
  locales/en.json
  public/mock-backend/api/private/config
  public/mock-backend/api/private/me-get
  src/api/auth/index.ts
  src/api/auth/ldap.ts
  src/api/auth/local.ts
  src/api/config/types.d.ts
  src/api/me/index.ts
  src/api/users/types.d.ts
  src/components/common/fields/current-password-field.tsx
  src/components/common/fields/display-name-field.tsx
  src/components/common/fields/fields.ts
  src/components/common/fields/new-password-field.tsx
  src/components/common/fields/password-again-field.tsx
  src/components/common/fields/username-field.tsx
  src/components/document-read-only-page/document-read-only-page-content.tsx
  src/components/editor-page/editor-pane/autocompletion/link-and-extra-tag.ts
  src/components/landing-layout/navigation/sign-in-button.tsx
  src/components/landing-layout/navigation/sign-out-dropdown-button.tsx
  src/components/landing-layout/navigation/user-dropdown.tsx
  src/components/login-page/auth/auth-error/auth-error.tsx
  src/components/login-page/auth/fields/fields.ts
  src/components/login-page/auth/fields/openid-field.tsx
  src/components/login-page/auth/fields/password-field.tsx
  src/components/login-page/auth/fields/username-field.tsx
  src/components/login-page/auth/utils.ts
  src/components/login-page/auth/via-ldap.tsx
  src/components/login-page/auth/via-local.tsx
  src/components/login-page/auth/via-openid.tsx
  src/components/login-page/login-page.tsx
  src/components/profile-page/profile-page.tsx
  src/components/profile-page/settings/profile-change-password.tsx
  src/components/profile-page/settings/profile-display-name.tsx
  src/components/register-page/register-error/register-error.tsx
  src/components/register-page/register-infos/register-infos.tsx
  src/components/register-page/register-page.tsx
  src/hooks/common/use-on-input-change.ts
  src/redux/config/reducers.ts
  src/redux/note-details/initial-state.ts
  src/redux/note-details/reducer.ts
  src/redux/note-details/types/note-details.ts
  src/redux/user/types.ts
Labels: type: code quality enhancement

#1666 Placeholder image
  CHANGELOG.md
  cypress/integration/autocompletion.spec.ts
  cypress/integration/fileUpload.spec.ts
  locales/en.json
  src/api/media/index.ts
  src/components/common/upload-image-mimetypes.ts
  src/components/editor-page/editor-pane/editor-pane.tsx
  src/components/editor-page/editor-pane/find-regex-match-in-text.test.ts
  src/components/editor-page/editor-pane/find-regex-match-in-text.ts
  src/components/editor-page/editor-pane/hooks/use-on-image-upload-from-renderer.ts
  src/components/editor-page/editor-pane/tool-bar/upload-image-button.tsx
  src/components/editor-page/editor-pane/upload-handler.ts
  src/components/markdown-renderer/document-markdown-renderer.tsx
  src/components/markdown-renderer/hooks/use-convert-markdown-to-react-dom.ts
  src/components/markdown-renderer/hooks/use-markdown-extensions.ts
  src/components/markdown-renderer/markdown-extension/image-placeholder/add-line-to-placeholder-image-tags.ts
  src/components/markdown-renderer/markdown-extension/image-placeholder/hooks/use-on-image-upload.ts
  src/components/markdown-renderer/markdown-extension/image-placeholder/hooks/use-placeholder-size-style.ts
  src/components/markdown-renderer/markdown-extension/image-placeholder/image-placeholder-markdown-extension.ts
  src/components/markdown-renderer/markdown-extension/image-placeholder/image-placeholder-replacer.tsx
  src/components/markdown-renderer/markdown-extension/image-placeholder/image-placeholder.scss
  src/components/markdown-renderer/markdown-extension/image-placeholder/image-placeholder.tsx
  src/components/markdown-renderer/markdown-extension/image-placeholder/utils/build-placeholder-size-css.test.ts
  src/components/markdown-renderer/markdown-extension/image-placeholder/utils/build-placeholder-size-css.ts
  src/components/markdown-renderer/markdown-extension/linemarker/linemarker-markdown-extension.ts
  src/components/markdown-renderer/markdown-extension/task-list/task-list-markdown-extension.ts
  src/components/markdown-renderer/markdown-extension/task-list/task-list-replacer.tsx
  src/components/markdown-renderer/markdown-extension/upload-indicating-image-frame/upload-indicating-frame.tsx
  src/components/markdown-renderer/markdown-extension/upload-indicating-image-frame/upload-indicating-image-frame-markdown-extension.ts
  src/components/markdown-renderer/markdown-extension/upload-indicating-image-frame/upload-indicating-image-frame-replacer.tsx
  src/components/markdown-renderer/replace-components/component-replacer.ts
  src/components/markdown-renderer/slideshow-markdown-renderer.tsx
  src/components/markdown-renderer/utils/node-to-react-transformer.tsx
  src/components/render-page/window-post-message-communicator/rendering-message.ts
  src/redux/note-details/methods.ts
  src/redux/note-details/reducer.ts
  src/redux/note-details/types.ts
Labels: type: feature

#1653 Update to cypress 9 and fix firefox upload crash
  cypress/fixtures/import.md
  cypress/fixtures/import.md.license
  cypress/fixtures/invalid-history.txt
  cypress/fixtures/invalid-history.txt.license
  cypress/integration/fileUpload.spec.ts
  cypress/integration/history.spec.ts
  cypress/integration/import.spec.ts
  package.json
  src/components/editor-page/sidebar/import-markdown-sidebar-entry.tsx
  src/components/editor-page/sidebar/upload-input.tsx
  yarn.lock
Labels: type: maintenance

#1681 Move markdown split into redux
  cypress/integration/maxLength.spec.ts
  src/components/document-read-only-page/document-read-only-page-content.tsx
  src/components/editor-page/app-bar/help-button/cheatsheet-line.tsx
  src/components/editor-page/app-bar/help-button/cheatsheet-tab-content.tsx
  src/components/editor-page/editor-document-renderer/editor-document-renderer.tsx
  src/components/editor-page/renderer-pane/hooks/use-send-markdown-to-renderer.ts
  src/components/editor-page/renderer-pane/render-iframe.tsx
  src/components/intro-page/hooks/use-intro-page-content.ts
  src/components/intro-page/intro-page.tsx
  src/components/markdown-renderer/common-markdown-renderer-props.ts
  src/components/markdown-renderer/document-length-limit-reached-alert.tsx
  src/components/markdown-renderer/document-markdown-renderer.tsx
  src/components/markdown-renderer/hooks/use-convert-markdown-to-react-dom.ts
  src/components/markdown-renderer/hooks/use-extract-first-headline.ts
  src/components/markdown-renderer/hooks/use-reveal.ts
  src/components/markdown-renderer/hooks/use-trimmed-content.ts
  src/components/markdown-renderer/slideshow-markdown-renderer.tsx
  src/components/markdown-renderer/utils/line-id-mapper.test.ts
  src/components/markdown-renderer/utils/line-id-mapper.ts
  src/components/render-page/iframe-markdown-renderer.tsx
  src/components/render-page/markdown-document.tsx
  src/components/render-page/window-post-message-communicator/rendering-message.ts
  src/components/slide-show-page/slide-show-page-content.tsx
  src/hooks/common/use-note-markdown-content-without-frontmatter.ts
  src/hooks/common/use-trimmed-note-markdown-content-without-frontmatter.ts
  src/redux/note-details/frontmatter-extractor/extractor.test.ts
  src/redux/note-details/frontmatter-extractor/extractor.ts
  src/redux/note-details/initial-state.ts
  src/redux/note-details/reducer.ts
  src/redux/note-details/types/note-details.ts
Labels: type: code quality enhancement

#1730 Remove asciinema
  CHANGELOG.md
  cypress/integration/linkEmbedder.spec.ts
  public/mock-backend/api/private/notes/ABC2/revisions/1598389571
  public/mock-backend/api/private/notes/ABC2/revisions/1598390307
  public/mock-backend/api/private/notes/features-get
  src/components/markdown-renderer/hooks/use-markdown-extensions.ts
  src/components/markdown-renderer/markdown-extension/asciinema/asciinema-frame.tsx
  src/components/markdown-renderer/markdown-extension/asciinema/asciinema-markdown-extension.ts
  src/components/markdown-renderer/markdown-extension/asciinema/replace-asciinema-link.ts
Labels: type: feature enhancement

#1729 fix: use actual noteTitle in DeleteNoteSidebarEntry
  cypress/integration/deleteNote.spec.ts
  src/components/common/modals/deletion-modal.tsx
  src/components/editor-page/sidebar/delete-note-sidebar-entry/delete-note-modal.tsx
  src/components/editor-page/sidebar/delete-note-sidebar-entry/delete-note-sidebar-entry.tsx
  src/components/editor-page/sidebar/sidebar.tsx
  src/components/editor-page/sidebar/specific-sidebar-entries/delete-note-sidebar-entry.tsx
Labels: type: bug, scope: editor

#1726 Use yarn berry
  .gitattributes
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .github/workflows/lint.yml
  .gitignore
  .reuse/dep5
  .yarn/releases/yarn-3.1.1.cjs
  .yarnrc.yml
  LICENSES/BSD-2-Clause.txt
  package.json
  yarn.lock
Labels: type: maintenance

#1735 Import emojis from scss and work around emoji bug on macos
  global-styles/index.scss
  global-styles/markdown-tweaks.scss
  global-styles/variables.module.scss
  global-styles/variables.scss
  src/components/editor-page/editor-pane/extended-codemirror/codemirror.module.scss
  src/components/editor-page/editor-pane/tool-bar/emoji-picker/emoji-picker.tsx
  src/components/markdown-renderer/markdown-extension/abcjs/abc.module.scss
  src/components/markdown-renderer/markdown-extension/flowchart/flowchart.tsx
Labels: type: bug

#1738 Added NEXT_PUBLIC_IGNORE_IFRAME_ORIGIN_CONFIG
  next.config.js
  src/components/application-loader/application-loader.tsx
  src/components/editor-page/render-context/renderer-to-editor-communicator-context-provider.tsx
  src/components/editor-page/render-context/use-origin-from-config.ts
  src/components/editor-page/renderer-pane/render-iframe.tsx
Labels: type: feature enhancement

#1739 Add etag header to last modified check of motd
  cypress/integration/motd.spec.ts
  src/components/application-loader/initializers/fetch-motd.ts
Labels: type: bug

#1736 Fix autocompletion
  cypress/integration/autocompletion.spec.ts
  src/components/editor-page/editor-pane/editor-pane.tsx
  src/components/editor-page/editor-pane/extended-codemirror/extended-codemirror.tsx
Labels: type: bug
