Repository hedgedoc/react-client, pull requests merged in 2021-08, with the labels that each got.

#1438 Fix code highlighting grid
  src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-code/highlighted-code.scss
Labels: type: bug, scope: renderer

#1460 Remove package "eslint-plugin-flowtype"
  package.json
  yarn.lock
Labels: type: maintenance

#1458 Optimize renovate config
  renovate.json
Labels: type: maintenance

#1464 Restructure CodeMirror imports + syntax highlighting
  src/components/editor-page/editor-pane/codemirror-imports.ts
  src/components/editor-page/editor-pane/editor-pane.tsx
Labels: type: feature enhancement, scope: editor, type: code quality enhancement

#1465 Rework notifications
  public/locales/en.json
  src/components/editor-page/editor-pane/autocompletion/code-block.ts
  src/components/editor-page/sidebar/pin-note-sidebar-entry.tsx
  src/components/editor-page/use-notification-test.tsx
  src/components/history-page/history-content/history-content.tsx
  src/components/history-page/history-page.tsx
  src/components/history-page/history-toolbar/clear-history-button.tsx
  src/components/history-page/history-toolbar/history-toolbar.tsx
  src/components/history-page/history-toolbar/import-history-button.tsx
  src/components/notifications/ui-notification-toast.tsx
  src/redux/ui-notifications/methods.ts
  src/redux/ui-notifications/reducers.ts
  src/redux/ui-notifications/types.ts
Labels: type: feature enhancement

#1467 Fix DoS in CSV parser
  src/components/markdown-renderer/replace-components/csv/csv-parser.ts
Labels: type: bug

#1469 Fix missing scrollbars for abcjs overflow
  src/components/markdown-renderer/replace-components/abc/abc.scss
Labels: type: bug, priority: 3 low

#1436 Replace custom gist implementation with github rendering
  CHANGELOG.md
  src/components/markdown-renderer/replace-components/gist/gist-frame.scss
  src/components/markdown-renderer/replace-components/gist/gist-frame.tsx
  src/components/markdown-renderer/replace-components/gist/use-resize-gist-frame.ts
Labels: type: feature enhancement

#1466 Replace i18next-http-backend with i18next-resources-to-backend
  .reuse/dep5
  locales/ar.json
  locales/ca.json
  locales/cs.json
  locales/da.json
  locales/de.json
  locales/el.json
  locales/en.json
  locales/eo.json
  locales/es.json
  locales/fr.json
  locales/hi.json
  locales/hr.json
  locales/id.json
  locales/it.json
  locales/ja.json
  locales/ko.json
  locales/nl.json
  locales/pl.json
  locales/pt.json
  locales/ru.json
  locales/sk.json
  locales/sr.json
  locales/sv.json
  locales/tr.json
  locales/uk.json
  locales/vi.json
  locales/zh-CN.json
  locales/zh-TW.json
  package.json
  src/components/application-loader/initializers/i18n/i18n.ts
  src/components/application-loader/initializers/index.ts
  yarn.lock
Labels: type: feature enhancement, type: code quality enhancement
