Repository hedgedoc/react-client, pull requests merged in 2021-01, with the labels that each got.

#900 Improve readme
  README.md
Labels: priority: 3 low, type: documentation

#901 Fix/prod build command
  README.md
  package.json
Labels: status: ready to merge, type: bug

#912 Open links always in new tabs
  src/components/markdown-renderer/hooks/use-replacer-instance-list-creator.ts
  src/components/markdown-renderer/markdown-it-plugins/headline-anchors.ts
  src/components/markdown-renderer/replace-components/external-links-in-new-tabs/external-links-in-new-tabs.tsx
Labels: priority: 1 high, type: feature

#911 Minor fixes
  cypress/support/config.ts
  public/api/v2/config
  src/components/editor/app-bar/dark-mode-button.tsx
  src/components/editor/app-bar/navbar-branding.tsx
  src/components/editor/document-bar/revisions/revision-modal.tsx
  src/components/editor/editor-pane/tool-bar/emoji-picker/emoji-picker.tsx
  src/components/editor/table-of-contents/table-of-contents.scss
  src/components/markdown-renderer/replace-components/abc/abc-frame.tsx
  src/components/markdown-renderer/replace-components/flow/flowchart/flowchart.tsx
  src/components/markdown-renderer/replace-components/graphviz/graphviz-frame.tsx
  src/components/markdown-renderer/replace-components/image/image-frame.tsx
  src/components/markdown-renderer/replace-components/image/lightboxedImageFrame.tsx
  src/hooks/common/use-apply-dark-mode.ts
  src/hooks/common/use-is-dark-mode-activated.ts
  src/style/index.scss
Labels: priority: 3 low, type: code quality enhancement

#874 Add ability to use yaml-array for tags
  CHANGELOG.md
  cypress/integration/metadata.spec.ts
  public/locales/en.json
  src/components/editor/yaml-metadata/yaml-metadata.test.ts
  src/components/editor/yaml-metadata/yaml-metadata.ts
  src/components/markdown-renderer/full-markdown-renderer.tsx
  src/components/markdown-renderer/replace-components/sequence-diagram/deprecation-warning.tsx
  src/redux/document-content/reducers.ts
Labels: scope: editor, type: feature enhancement

#913 Relicense locales under CC-BY-SA
  .reuse/dep5
Labels: priority: 1 high, type: feature enhancement

#902 Feature/browserstack
  .github/workflows/e2e.yml
  README.md
  browserstack.json
  browserstack.json.license
  cypress/fixtures/import.md.txt
  cypress/fixtures/import.md.txt.license
  cypress/integration/maxLength.spec.ts
  cypress/integration/upload.spec.ts
  cypress/support/fill.ts
  cypress/support/index.ts
  cypress/tsconfig.json
  package.json
  src/components/editor/editorTestContent.ts
  src/components/markdown-renderer/replace-components/markmap/markmap-frame.tsx
  src/components/markdown-renderer/replace-components/mermaid/mermaid-chart.tsx
  yarn.lock
Labels: priority: 2 medium, type: feature enhancement

#919 Use yaml-array in demo content
  src/components/editor/editorTestContent.ts
Labels: priority: 3 low, scope: editor, status: ready to merge, type: feature enhancement

#916 Move yaml-array warning to documentrenderpane
  src/components/editor/document-renderer-pane/document-render-pane.tsx
  src/components/editor/document-renderer-pane/scrolling-document-render-pane.tsx
  src/components/editor/document-renderer-pane/use-adapted-line-markers-callback.ts
  src/components/markdown-renderer/full-markdown-renderer.tsx
Labels: status: ready to merge, type: code quality enhancement

#921 added shortcut for addLink (ctrl+k)
  CHANGELOG.md
  public/locales/en.json
  src/components/editor/app-bar/help-button/shortcuts.tsx
  src/components/editor/editor-pane/key-map.ts
Labels: scope: editor, status: ready to merge, type: feature enhancement

#920 fixed toolbarButtonUtils.test.ts
  src/components/editor/editor-pane/tool-bar/utils/toolbarButtonUtils.test.ts
Labels: status: ready to merge, type: code quality enhancement

#915 Fix yaml metadata and document title not resetting on deletion
  src/components/markdown-renderer/basic-markdown-renderer.tsx
  src/components/markdown-renderer/full-markdown-renderer.tsx
  src/components/markdown-renderer/hooks/use-extract-first-headline.ts
  src/components/markdown-renderer/markdown-it-configurator/FullMarkdownItConfigurator.tsx
  src/redux/document-content/methods.ts
Labels: status: ready to merge, type: bug

#914 Use original markdown-it-anchor
  package.json
  src/components/markdown-renderer/markdown-it-plugins/headline-anchors.ts
  yarn.lock
Labels: type: maintenance

#922 Activate "maintainLockFilesWeekly" in renovate config
  renovate.json
Labels: type: maintenance

#923 Limit lightbox size
  src/components/markdown-renderer/replace-components/image/lightbox.scss
  src/components/markdown-renderer/replace-components/image/lightboxedImageFrame.tsx
Labels: priority: 2 medium, scope: renderer, status: ready to merge, type: feature enhancement

#942 Don't show "create table" overlay if modal is showing
  src/components/editor/editor-pane/tool-bar/table-picker/table-picker.tsx
Labels: priority: 1 high, scope: editor, status: ready to merge, type: bug

#935 Add branch info to browserstack runs
  .github/workflows/e2e.yml
  README.md
  browserstack.json
Labels: status: ready to merge, type: maintenance

#944 Improve tests
  .editorconfig
  cypress/integration/autocompletion.spec.ts
  cypress/integration/code.spec.ts
  cypress/integration/documentTitle.spec.ts
  cypress/integration/editorMode.spec.ts
  cypress/integration/export.spec.ts
  cypress/integration/fileUpload.spec.ts
  cypress/integration/import.spec.ts
  cypress/integration/maxLength.spec.ts
  cypress/integration/metadata.spec.ts
  cypress/integration/toolbar.spec.ts
  cypress/integration/yamlArrayDeprecationMessage.spec.ts
  src/components/common/modals/common-modal.tsx
  src/components/editor/document-renderer-pane/document-render-pane.tsx
  src/components/editor/document-renderer-pane/yaml-array-deprecation-alert.tsx
  src/components/editor/editor-modals/max-length-warning-modal.tsx
  src/components/editor/editor-pane/status-bar/status-bar.tsx
  src/components/markdown-renderer/basic-markdown-renderer.tsx
  src/components/markdown-renderer/replace-components/sequence-diagram/deprecation-warning.tsx
  src/index.tsx
Labels: priority: 1 high, type: code quality enhancement

#946 fixed title extraction to exclude latex code, but include rendered latex
  cypress/integration/documentTitle.spec.ts
  src/components/markdown-renderer/hooks/use-extract-first-headline.ts
Labels: priority: 2 medium, status: ready to merge, type: bug

#947 added a spoiler container
  cypress/integration/autocompletion.spec.ts
  cypress/integration/toolbar.spec.ts
  src/components/editor/editor-pane/autocompletion/container.ts
  src/components/editor/editor-pane/autocompletion/index.ts
  src/components/editor/editor-pane/tool-bar/utils/toolbarButtonUtils.test.ts
  src/components/editor/editor-pane/tool-bar/utils/toolbarButtonUtils.ts
  src/components/markdown-renderer/markdown-it-configurator/BasicMarkdownItConfigurator.tsx
  src/components/markdown-renderer/markdown-it-plugins/alert-container.ts
  src/components/markdown-renderer/markdown-it-plugins/spoiler-container.ts
Labels: scope: editor, status: ready to merge, type: feature

#943 Fix counter continue in highlighted-fence-replacer.tsx
  cypress/integration/code.spec.ts
  cypress/integration/highlightedCodeBlock.spec.ts
  src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-code/highlighted-code.scss
  src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-code/highlighted-code.tsx
  src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-fence-replacer.tsx
Labels: priority: 0 critical, scope: renderer, status: ready to merge, type: bug

#948 Rewrite tests
  cypress/integration/autocompletion.spec.ts
  cypress/integration/documentTitle.spec.ts
  cypress/integration/export.spec.ts
  cypress/integration/fileUpload.spec.ts
  cypress/integration/helpDialog.spec.ts
  cypress/integration/highlightedCodeBlock.spec.ts
  cypress/integration/import.spec.ts
  cypress/integration/maxLength.spec.ts
  cypress/integration/toolbar.spec.ts
  cypress/integration/yamlArrayDeprecationMessage.spec.ts
  cypress/support/fill.ts
  src/components/editor/editor-pane/tool-bar/emoji-picker/emoji-picker-button.tsx
  src/components/editor/editor-pane/tool-bar/table-picker/table-picker-button.tsx
  src/components/editor/editor-pane/tool-bar/table-picker/table-picker.tsx
  src/components/editor/editor-pane/tool-bar/tool-bar.tsx
Labels: priority: 2 medium, status: ready to merge, type: code quality enhancement

#949 Removed some types as the package comes with it own types now
  package.json
  src/external-types/markdown-it-front-matter/index.d.ts
  src/external-types/markdown-it-plantuml/index.d.ts
  src/external-types/markdown-it-plantuml/interface.d.ts
  yarn.lock
Labels: status: ready to merge, type: code quality enhancement

#950 Limit attributes for external links
  src/components/markdown-renderer/replace-components/external-links-in-new-tabs/external-links-in-new-tabs.tsx
Labels: priority: 1 high, scope: renderer, status: ready to merge, type: feature enhancement

#962 Collected minor changes from #837
  src/components/editor/document-renderer-pane/document-render-pane.tsx
  src/components/editor/document-renderer-pane/yaml-array-deprecation-alert.tsx
  src/components/markdown-renderer/basic-markdown-renderer.tsx
  src/components/markdown-renderer/document-length-limit-reached-alert.tsx
  src/components/markdown-renderer/full-markdown-renderer.tsx
  src/components/markdown-renderer/hooks/use-convert-markdown-to-react-dom.ts
  src/components/markdown-renderer/markdown-renderer.scss
  src/components/markdown-renderer/replace-components/ComponentReplacer.ts
  src/components/markdown-renderer/replace-components/image/image-lightbox-modal.tsx
  src/components/markdown-renderer/replace-components/image/image-replacer.tsx
  src/components/markdown-renderer/replace-components/image/lightbox-image-frame.tsx
  src/components/markdown-renderer/replace-components/image/lightboxedImageFrame.tsx
  src/components/markdown-renderer/replace-components/image/proxy-image-frame.tsx
  src/components/markdown-renderer/replace-components/sequence-diagram/deprecation-warning.tsx
  src/components/markdown-renderer/utils/html-react-transformer.tsx
  src/hooks/common/use-apply-dark-mode.ts
Labels: priority: 1 high, status: ready to merge, type: code quality enhancement, type: feature enhancement

#975 Update abc js to version 6-beta
  package.json
  src/components/markdown-renderer/replace-components/abc/abc-frame.tsx
  src/components/markdown-renderer/replace-components/abc/abc.scss
  src/style/index.scss
  src/style/variables.scss
  yarn.lock
Labels: priority: 2 medium, scope: renderer, type: maintenance

#837 Wrap markdown rendering in iframe
  CHANGELOG.md
  cypress/integration/autocompletion.spec.ts
  cypress/integration/documentTitle.spec.ts
  cypress/integration/highlightedCodeBlock.spec.ts
  cypress/integration/maxLength.spec.ts
  cypress/integration/yamlArrayDeprecationMessage.spec.ts
  cypress/support/config.ts
  cypress/support/getMarkdownRenderer.ts
  cypress/support/index.ts
  public/api/v2/config
  src/api/config/types.d.ts
  src/components/common/copyable/copy-to-clipboard-button/copy-to-clipboard-button.tsx
  src/components/common/download/download.ts
  src/components/editor/document-renderer-pane/document-iframe.tsx
  src/components/editor/document-renderer-pane/document-render-pane.tsx
  src/components/editor/document-renderer-pane/scrolling-document-render-pane.tsx
  src/components/editor/document-renderer-pane/use-adapted-line-markers-callback.ts
  src/components/editor/document-renderer-pane/yaml-array-deprecation-alert.tsx
  src/components/editor/editor.tsx
  src/components/editor/scroll/hooks/use-on-user-scroll.ts
  src/components/editor/splitter/splitter.tsx
  src/components/editor/table-of-contents/table-of-contents.scss
  src/components/editor/table-of-contents/table-of-contents.tsx
  src/components/history-page/history-page.tsx
  src/components/markdown-renderer/full-markdown-renderer.tsx
  src/components/markdown-renderer/hooks/use-convert-markdown-to-react-dom.ts
  src/components/markdown-renderer/hooks/use-replacer-instance-list-creator.ts
  src/components/markdown-renderer/markdown-it-configurator/FullMarkdownItConfigurator.tsx
  src/components/markdown-renderer/replace-components/external-links-in-new-tabs/external-links-in-new-tabs.tsx
  src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-code/highlighted-code.tsx
  src/components/markdown-renderer/replace-components/image/image-lightbox-modal.tsx
  src/components/markdown-renderer/replace-components/image/image-replacer.tsx
  src/components/markdown-renderer/replace-components/image/lightbox-image-frame.tsx
  src/components/markdown-renderer/replace-components/image/proxy-image-frame.tsx
  src/components/markdown-renderer/replace-components/link-replacer/link-replacer.tsx
  src/components/markdown-renderer/utils/html-react-transformer.tsx
  src/components/pad-view-only/pad-view-only.tsx
  src/components/render-page/iframe-communicator.ts
  src/components/render-page/iframe-editor-to-renderer-communicator.ts
  src/components/render-page/iframe-renderer-to-editor-communicator.ts
  src/components/render-page/render-page.tsx
  src/components/render-page/rendering-message.ts
  src/index.tsx
  src/redux/config/reducers.ts
  src/style/index.scss
Labels: priority: 0 critical, scope: renderer, type: feature enhancement

#937 Replace document bar with sidebar
  CHANGELOG.md
  cypress/integration/export.spec.ts
  cypress/integration/import.spec.ts
  cypress/integration/toolbar.spec.ts
  public/locales/en.json
  src/components/common/hidden-input-menu-entry/hidden-input-menu-entry.tsx
  src/components/common/user-avatar/user-avatar.tsx
  src/components/editor/app-bar/app-bar.tsx
  src/components/editor/document-bar/buttons/pin-to-history-button.tsx
  src/components/editor/document-bar/buttons/share-link-button.tsx
  src/components/editor/document-bar/connection-indicator/connection-indicator.tsx
  src/components/editor/document-bar/connection-indicator/user-line.scss
  src/components/editor/document-bar/document-bar.tsx
  src/components/editor/document-bar/document-info/document-info-modal.tsx
  src/components/editor/document-bar/menus/editor-menu.tsx
  src/components/editor/document-bar/menus/export-menu.tsx
  src/components/editor/document-bar/menus/export/markdown.tsx
  src/components/editor/document-bar/menus/import-menu.tsx
  src/components/editor/document-bar/permissions/permission-button.tsx
  src/components/editor/document-bar/permissions/permission-modal.tsx
  src/components/editor/document-bar/revisions/revision-button.tsx
  src/components/editor/document-bar/revisions/revision-modal.tsx
  src/components/editor/document-bar/share/share-modal.tsx
  src/components/editor/document-renderer-pane/document-render-pane.tsx
  src/components/editor/editor-pane/editor-pane.tsx
  src/components/editor/editor-pane/tool-bar/tool-bar.tsx
  src/components/editor/editor-pane/tool-bar/upload-image-button.tsx
  src/components/editor/editor.tsx
  src/components/editor/sidebar/delete-note-sidebar-entry.tsx
  src/components/editor/sidebar/document-info-sidebar-entry.tsx
  src/components/editor/sidebar/export-markdown-sidebar-entry.tsx
  src/components/editor/sidebar/export-menu-sidebar-menu.tsx
  src/components/editor/sidebar/import-markdown-sidebar-entry.tsx
  src/components/editor/sidebar/import-menu-sidebar-menu.tsx
  src/components/editor/sidebar/permissions-sidebar-entry.tsx
  src/components/editor/sidebar/pin-note-sidebar-entry.tsx
  src/components/editor/sidebar/revision-sidebar-entry.tsx
  src/components/editor/sidebar/share-sidebar-entry.tsx
  src/components/editor/sidebar/sidebar-button.tsx
  src/components/editor/sidebar/sidebar-menu.tsx
  src/components/editor/sidebar/sidebar.tsx
  src/components/editor/sidebar/style/colors.scss
  src/components/editor/sidebar/style/layout.scss
  src/components/editor/sidebar/style/theme.scss
  src/components/editor/sidebar/types.ts
  src/components/editor/sidebar/upload-input.tsx
  src/components/editor/sidebar/users-online-sidebar-menu/active-indicator.scss
  src/components/editor/sidebar/users-online-sidebar-menu/active-indicator.tsx
  src/components/editor/sidebar/users-online-sidebar-menu/online-counter.scss
  src/components/editor/sidebar/users-online-sidebar-menu/user-line.scss
  src/components/editor/sidebar/users-online-sidebar-menu/user-line.tsx
  src/components/editor/sidebar/users-online-sidebar-menu/users-online-sidebar-menu.tsx
  src/components/editor/table-of-contents/table-of-contents.scss
  src/components/markdown-renderer/hooks/use-post-toc-ast-on-change.ts
Labels: priority: 1 high, scope: editor, type: feature enhancement

#981 change domain in build:serve script
  package.json
Labels: status: ready to merge

#980 ABCFrame text-color is always black
  src/components/markdown-renderer/replace-components/abc/abc-frame.tsx
Labels: scope: renderer, status: ready to merge, type: bug

#996 Include markmap-common in renovate group
  renovate.json
Labels: priority: 1 high, type: maintenance

#997 Use currentColor in SVGs
  src/components/editor/app-bar/sync-scroll-buttons/disabledScroll.svg
  src/components/editor/app-bar/sync-scroll-buttons/enabledScroll.svg
Labels: priority: 3 low, status: ready to merge, type: feature enhancement

#1000 Remove PDF embedding
  CHANGELOG.md
  src/components/markdown-renderer/hooks/use-replacer-instance-list-creator.ts
  src/components/markdown-renderer/markdown-it-configurator/FullMarkdownItConfigurator.tsx
  src/components/markdown-renderer/regex-plugins/replace-legacy-pdf-short-code.ts
  src/components/markdown-renderer/regex-plugins/replace-legacy-slideshare-short-code.ts
  src/components/markdown-renderer/regex-plugins/replace-legacy-speakerdeck-short-code.ts
  src/components/markdown-renderer/replace-components/pdf/pdf-frame.scss
  src/components/markdown-renderer/replace-components/pdf/pdf-frame.tsx
  src/components/markdown-renderer/replace-components/pdf/pdf-replacer.tsx
  src/components/markdown-renderer/replace-components/pdf/replace-pdf-short-code.ts
Labels: priority: 1 high, scope: renderer, type: feature enhancement
