Repository hedgedoc/react-client, pull requests merged in 2021-05, with the labels that each got.

#1230 Restructures + New Evironment Variables
  .github/workflows/build.yml
  .reuse/dep5
  README.md
  cypress/integration/fileUpload.spec.ts
  cypress/integration/history.spec.ts
  cypress/integration/intro.spec.ts
  cypress/integration/profile.spec.ts
  cypress/integration/signInButton.spec.ts
  cypress/support/config.ts
  cypress/support/visit-test-editor.ts
  package.json
  public/api/private/notes/features-get
  public/img/demo.png.license
  public/index.html
  public/mock-backend/api/private/config
  public/mock-backend/api/private/me-get
  public/mock-backend/api/private/me/history
  public/mock-backend/api/private/notes/banner-get
  public/mock-backend/api/private/notes/features-get
  public/mock-backend/api/private/notes/features/revisions-list
  public/mock-backend/api/private/notes/features/revisions/1598389571
  public/mock-backend/api/private/notes/features/revisions/1598390307
  public/mock-backend/api/private/notes/old-get
  public/mock-backend/api/private/tokens
  public/mock-backend/api/private/users/dermolly
  public/mock-backend/api/private/users/emcrx
  public/mock-backend/api/private/users/mrdrogdrog
  public/mock-backend/public/img/avatar.png
  public/mock-backend/public/img/demo.png
  public/mock-backend/public/img/highres.jpg
  public/mock-backend/public/intro.md
  public/mock-backend/public/screenshot.png
  public/screenshot.png.license
  src/components/application-loader/application-loader.tsx
  src/components/application-loader/initializers/fetch-frontend-config.ts
  src/components/application-loader/initializers/i18n.ts
  src/components/application-loader/initializers/index.ts
  src/components/intro-page/hooks/use-intro-page-content.ts
  src/components/intro-page/requests.ts
  src/components/landing-layout/footer/powered-by-links.tsx
  src/components/login-page/auth/utils.ts
  src/components/login-page/auth/via-internal.tsx
  src/components/login-page/auth/via-ldap.tsx
  src/components/login-page/auth/via-openid.tsx
  src/components/markdown-renderer/replace-components/graphviz/graphviz-frame.tsx
  src/components/profile-page/settings/profile-display-name.tsx
  src/components/register-page/register-page.tsx
  src/hooks/common/use-backend-base-url.ts
  src/hooks/common/use-customize-assets-url.ts
  src/hooks/common/use-frontend-assets-url.ts
  src/index.tsx
  src/utils/test-modes.ts
Labels: type: feature enhancement

#1221 Don't show error if no intro.md was found
  cypress/integration/intro.spec.ts
  src/components/intro-page/hooks/use-intro-page-content.ts
  src/components/intro-page/intro-page.tsx
Labels: scope: intro, type: feature enhancement

#1216 Fetch banner.txt from public URL instead of config
  cypress/fixtures/banner.txt
  cypress/fixtures/banner.txt.license
  cypress/integration/banner.spec.ts
  cypress/support/config.ts
  public/mock-backend/api/private/notes/banner-get
  public/mock-backend/public/banner.txt
  src/api/config/types.d.ts
  src/components/application-loader/initializers/fetch-and-set-banner.ts
  src/components/application-loader/initializers/fetch-frontend-config.ts
  src/components/application-loader/initializers/index.ts
  src/components/common/motd-banner/motd-banner.tsx
  src/redux/banner/reducers.ts
  src/redux/banner/types.ts
  src/redux/config/reducers.ts
Labels: status: ready to merge, type: feature enhancement

#1232 Fix spinner visibility on intro-page
  src/components/intro-page/intro-page.tsx
Labels: type: bug

#1233 Fix task list checkboxes for numbered lists
  cypress/integration/taskLists.spec.ts
  src/redux/note-details/reducers.ts
Labels: priority: 1 high, scope: renderer, status: ready to merge, type: bug

#1158 The History PR: III - Editor integration
  CHANGELOG.md
  src/components/editor-page/editor-page.tsx
  src/components/editor-page/hooks/useUpdateLocalHistoryEntry.ts
  src/components/editor-page/sidebar/pin-note-sidebar-entry.tsx
  src/components/editor-page/sidebar/style/colors.scss
Labels: scope: editor, type: feature

#1238 Replace bash dependency with nodejs script
  check-build-env-vars.js
  package.json
Labels: type: code quality enhancement

#1237 Change schema of url environment variables
  package.json
  src/api/auth/index.ts
  src/api/config/index.ts
  src/api/history/index.ts
  src/api/me/index.ts
  src/api/media/index.ts
  src/api/notes/index.ts
  src/api/revisions/index.ts
  src/api/tokens/index.ts
  src/components/application-loader/initializers/fetch-and-set-banner.ts
  src/components/application-loader/initializers/i18n.ts
  src/components/application-loader/initializers/index.ts
  src/components/intro-page/requests.ts
  src/components/landing-layout/navigation/sign-in-button.tsx
  src/components/profile-page/settings/profile-account-management.tsx
  src/hooks/common/use-backend-base-url.ts
  src/hooks/common/use-customize-assets-url.ts
  src/hooks/common/use-frontend-base-url.ts
Labels: type: feature enhancement

#1276 Update node to 16
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .github/workflows/lint.yml
  .nvmrc
  README.md
  package.json
  yarn.lock
Labels: type: code quality enhancement

#1288 Activate renovate dependency dashboard
  renovate.json
Labels: type: maintenance
