Repository hedgedoc/react-client, pull requests merged in 2021-09, with the labels that each got.

#1413 Move frontmatter extraction from renderer to redux
  package.json
  src/api/notes/dto-methods.ts
  src/components/common/note-frontmatter/extract-frontmatter.test.ts
  src/components/common/note-frontmatter/extract-frontmatter.ts
  src/components/common/note-frontmatter/note-frontmatter.test.ts
  src/components/common/note-frontmatter/note-frontmatter.ts
  src/components/common/note-frontmatter/types.ts
  src/components/document-read-only-page/document-read-only-page.tsx
  src/components/editor-page/app-bar/app-bar.tsx
  src/components/editor-page/document-bar/share/share-modal.tsx
  src/components/editor-page/editor-page.tsx
  src/components/editor-page/note-frontmatter/note-frontmatter.test.ts
  src/components/editor-page/renderer-pane/render-iframe.tsx
  src/components/editor-page/renderer-pane/yaml-array-deprecation-alert.tsx
  src/components/editor-page/sidebar/export-markdown-sidebar-entry.tsx
  src/components/editor-page/sidebar/import-markdown-sidebar-entry.tsx
  src/components/markdown-renderer/basic-markdown-renderer.tsx
  src/components/markdown-renderer/hooks/use-component-replacers.ts
  src/components/markdown-renderer/markdown-it-configurator/BasicMarkdownItConfigurator.tsx
  src/components/markdown-renderer/markdown-it-plugins/frontmatter.ts
  src/components/markdown-renderer/replace-components/linemarker/line-number-marker.ts
  src/components/markdown-renderer/replace-components/task-list/task-list-replacer.tsx
  src/components/render-page/iframe-editor-to-renderer-communicator.ts
  src/components/render-page/iframe-markdown-renderer.tsx
  src/components/render-page/iframe-renderer-to-editor-communicator.ts
  src/components/render-page/markdown-document.tsx
  src/components/render-page/rendering-message.ts
  src/redux/index.ts
  src/redux/note-details/initial-state.ts
  src/redux/note-details/methods.ts
  src/redux/note-details/reducer.ts
  src/redux/note-details/reducers.ts
  src/redux/note-details/types.ts
  yarn.lock
Labels: scope: editor, type: code quality enhancement, scope: renderer

#1484 Replace imsize with @hedgedoc/markdown-it-image-size
  package.json
  src/components/markdown-renderer/markdown-it-configurator/BasicMarkdownItConfigurator.tsx
  src/external-types/markdown-it-imsize/index.d.ts
  src/external-types/markdown-it-imsize/interface.ts
  yarn.lock
Labels: type: code quality enhancement

#1470 Remove document content
  src/components/document-read-only-page/document-read-only-page.tsx
  src/components/editor-page/editor-document-renderer/editor-document-renderer.tsx
  src/components/editor-page/editor-page.tsx
  src/components/editor-page/editor-pane/editor-pane.tsx
  src/components/editor-page/sidebar/export-markdown-sidebar-entry.tsx
  src/hooks/common/use-note-markdown-content-without-frontmatter.ts
  src/hooks/common/use-note-markdown-content.ts
  src/redux/note-details/initial-state.ts
  src/redux/note-details/reducer.ts
  src/redux/note-details/types.ts
Labels: type: bug, type: feature enhancement

#1487 Remove unneeded props interface
  src/components/editor-page/editor-pane/editor-pane.tsx
Labels: type: code quality enhancement

#1488 Remove deprecated code in basic markdown-it configurator
  src/components/markdown-renderer/basic-markdown-renderer.tsx
  src/components/markdown-renderer/markdown-it-configurator/basic-markdown-it-configurator.ts
Labels: type: code quality enhancement

#1510 Restructure Communicator
  src/components/document-read-only-page/document-read-only-page.tsx
  src/components/editor-page/document-bar/document-info/document-info-line-word-count.tsx
  src/components/editor-page/editor-document-renderer/editor-document-renderer.tsx
  src/components/editor-page/editor-page.tsx
  src/components/editor-page/render-context/editor-to-renderer-communicator-context-provider.tsx
  src/components/editor-page/render-context/iframe-editor-to-renderer-communicator-context-provider.tsx
  src/components/editor-page/render-context/iframe-renderer-to-editor-communicator-context-provider.tsx
  src/components/editor-page/render-context/renderer-to-editor-communicator-context-provider.tsx
  src/components/editor-page/renderer-pane/communicator-image-lightbox.tsx
  src/components/editor-page/renderer-pane/hooks/use-on-iframe-load.ts
  src/components/editor-page/renderer-pane/hooks/use-send-dark-mode-status-to-renderer.ts
  src/components/editor-page/renderer-pane/hooks/use-send-frontmatter-info-from-redux-to-renderer.ts
  src/components/editor-page/renderer-pane/hooks/use-send-markdown-to-renderer.ts
  src/components/editor-page/renderer-pane/hooks/use-send-scroll-state.ts
  src/components/editor-page/renderer-pane/render-iframe.tsx
  src/components/editor-page/renderer-pane/show-on-prop-change-image-lightbox.tsx
  src/components/intro-page/intro-page.tsx
  src/components/render-page/hooks/use-image-click-handler.ts
  src/components/render-page/iframe-editor-to-renderer-communicator.ts
  src/components/render-page/iframe-markdown-renderer.tsx
  src/components/render-page/iframe-renderer-to-editor-communicator.ts
  src/components/render-page/render-page.tsx
  src/components/render-page/window-post-message-communicator/editor-to-renderer-communicator.ts
  src/components/render-page/window-post-message-communicator/hooks/use-editor-receive-handler.ts
  src/components/render-page/window-post-message-communicator/hooks/use-effect-on-renderer-ready.ts
  src/components/render-page/window-post-message-communicator/hooks/use-is-renderer-ready.ts
  src/components/render-page/window-post-message-communicator/hooks/use-renderer-receive-handler.ts
  src/components/render-page/window-post-message-communicator/hooks/use-send-to-renderer.ts
  src/components/render-page/window-post-message-communicator/renderer-to-editor-communicator.ts
  src/components/render-page/window-post-message-communicator/rendering-message.ts
  src/components/render-page/window-post-message-communicator/window-post-message-communicator.ts
Labels: type: code quality enhancement

#1519 Add logging
  CONTRIBUTING.md
  src/components/application-loader/application-loader.tsx
  src/components/application-loader/initializers/fetch-and-set-banner.ts
  src/components/common/copyable/copy-overlay.tsx
  src/components/common/copyable/copyable-field/copyable-field.tsx
  src/components/editor-page/document-bar/revisions/utils.ts
  src/components/editor-page/editor-page.tsx
  src/components/editor-page/editor-pane/autocompletion/code-block.ts
  src/components/editor-page/editor-pane/autocompletion/emoji.ts
  src/components/editor-page/editor-pane/upload-handler.ts
  src/components/editor-page/hooks/useLoadNoteFromServer.ts
  src/components/editor-page/renderer-pane/hooks/use-on-iframe-load.ts
  src/components/editor-page/sidebar/upload-input.tsx
  src/components/editor-page/use-notification-test.tsx
  src/components/error-boundary/error-boundary.tsx
  src/components/landing-layout/footer/language-picker.tsx
  src/components/markdown-renderer/markdown-it-plugins/parser-debugger.ts
  src/components/markdown-renderer/replace-components/abc/abc-frame.tsx
  src/components/markdown-renderer/replace-components/flow/flowchart/flowchart.tsx
  src/components/markdown-renderer/replace-components/graphviz/graphviz-frame.tsx
  src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-code/highlighted-code.tsx
  src/components/markdown-renderer/replace-components/image/proxy-image-frame.tsx
  src/components/markdown-renderer/replace-components/markmap/markmap-frame.tsx
  src/components/markdown-renderer/replace-components/mermaid/mermaid-chart.tsx
  src/components/markdown-renderer/replace-components/one-click-frame/one-click-embedding.tsx
  src/components/markdown-renderer/replace-components/vega-lite/vega-chart.tsx
  src/components/notifications/ui-notification-toast.tsx
  src/components/profile-page/access-tokens/profile-access-tokens.tsx
  src/components/register-page/register-page.tsx
  src/components/render-page/window-post-message-communicator/editor-to-renderer-communicator.ts
  src/components/render-page/window-post-message-communicator/renderer-to-editor-communicator.ts
  src/components/render-page/window-post-message-communicator/window-post-message-communicator.ts
  src/index.tsx
  src/redux/dark-mode/methods.ts
  src/redux/editor/methods.ts
  src/redux/history/methods.ts
  src/redux/ui-notifications/methods.ts
  src/service-worker-registration.ts
  src/service-worker.ts
  src/utils/logger.test.ts
  src/utils/logger.ts
Labels: type: feature, status: ready to merge
