Repository hedgedoc/react-client, pull requests merged in 2021-11, with the labels that each got.

#1609 Dom purify
  cypress/integration/linkSchemes.spec.ts
  package.json
  src/components/markdown-renderer/hooks/dom-purifier-node-preprocessor.ts
  src/components/markdown-renderer/hooks/use-convert-markdown-to-react-dom.ts
  src/components/markdown-renderer/process-reveal-comment-nodes.ts
  src/components/markdown-renderer/regex-plugins/replace-legacy-slideshare-short-code.ts
  src/components/markdown-renderer/replace-components/katex/katex-replacer.tsx
  src/components/markdown-renderer/replace-components/link-replacer/link-replacer.tsx
  yarn.lock
Labels: type: feature

#1585 feat: add a target description to OneClickEmbedding
  locales/en.json
  src/components/markdown-renderer/replace-components/asciinema/asciinema-frame.tsx
  src/components/markdown-renderer/replace-components/gist/gist-frame.tsx
  src/components/markdown-renderer/replace-components/one-click-frame/one-click-embedding.tsx
  src/components/markdown-renderer/replace-components/vimeo/vimeo-frame.tsx
  src/components/markdown-renderer/replace-components/youtube/youtube-frame.tsx
Labels: type: feature enhancement, status: ready to merge

#1611 Restructure click shield
  cypress/integration/linkEmbedder.spec.ts
  cypress/integration/shortcodes.spec.ts
  locales/en.json
  src/components/markdown-renderer/replace-components/asciinema/asciinema-frame.tsx
  src/components/markdown-renderer/replace-components/click-shield/click-shield.scss
  src/components/markdown-renderer/replace-components/click-shield/click-shield.tsx
  src/components/markdown-renderer/replace-components/gist/gist-frame.scss
  src/components/markdown-renderer/replace-components/gist/gist-frame.tsx
  src/components/markdown-renderer/replace-components/gist/gist-preview.png
  src/components/markdown-renderer/replace-components/gist/gist-preview.png.license
  src/components/markdown-renderer/replace-components/one-click-frame/one-click-embedding.tsx
  src/components/markdown-renderer/replace-components/vimeo/vimeo-frame.tsx
  src/components/markdown-renderer/replace-components/youtube/youtube-frame.tsx
Labels: type: bug

#1634 Cypress-IDs and prettier for tests
  cypress/integration/autocompletion.spec.ts
  cypress/integration/diagrams.spec.ts
  cypress/integration/document-read-only-page.spec.ts
  cypress/integration/documentTitle.spec.ts
  cypress/integration/editorMode.spec.ts
  cypress/integration/emoji.spec.ts
  cypress/integration/export.spec.ts
  cypress/integration/fileUpload.spec.ts
  cypress/integration/helpDialog.spec.ts
  cypress/integration/highlightedCodeBlock.spec.ts
  cypress/integration/history.spec.ts
  cypress/integration/import.spec.ts
  cypress/integration/intro.spec.ts
  cypress/integration/language.spec.ts
  cypress/integration/link.spec.ts
  cypress/integration/linkEmbedder.spec.ts
  cypress/integration/maxLength.spec.ts
  cypress/integration/motd.spec.ts
  cypress/integration/profile.spec.ts
  cypress/integration/quote-extra.spec.ts
  cypress/integration/shortcodes.spec.ts
  cypress/integration/signInButton.spec.ts
  cypress/integration/slideshow-only-page.spec.ts
  cypress/integration/splitter.spec.ts
  cypress/integration/taskLists.spec.ts
  cypress/integration/toolbar.spec.ts
  cypress/integration/word-count.spec.ts
  cypress/integration/yamlArrayDeprecationMessage.spec.ts
  cypress/support/checkLinks.ts
  cypress/support/config.ts
  cypress/support/fill.ts
  cypress/support/get-by-id.ts
  cypress/support/index.ts
  cypress/support/login.ts
  cypress/support/visit-test-editor.ts
  package.json
  src/components/common/modals/deletion-modal.tsx
  src/components/common/modals/error-modal.tsx
  src/components/editor-page/app-bar/help-button/help-button.tsx
  src/components/editor-page/editor-pane/tool-bar/upload-image-button.tsx
  src/components/history-page/history-card/history-card.tsx
  src/components/history-page/pin-button/pin-button.tsx
  src/components/landing-layout/footer/language-picker.tsx
  src/components/landing-layout/navigation/header-bar/header-bar.tsx
  src/components/landing-layout/navigation/header-nav-link.tsx
  src/components/landing-layout/navigation/new-guest-note-button.tsx
  src/components/landing-layout/navigation/new-user-note-button.tsx
  src/components/landing-layout/navigation/user-dropdown.tsx
  src/components/markdown-renderer/markdown-extension/abcjs/abc-frame.tsx
  src/components/markdown-renderer/markdown-extension/csv/csv-table.tsx
  src/components/markdown-renderer/markdown-extension/highlighted-fence/highlighted-code.tsx
  src/components/markdown-renderer/markdown-extension/plantuml/plantuml-markdown-extension.ts
  src/components/profile-page/access-tokens/profile-access-tokens.tsx
Labels: type: code quality enhancement

#1647 Fix renderer type test
  cypress/integration/intro.spec.ts
  cypress/integration/renderer-mode.spec.ts
  cypress/support/get-iframe-content.ts
  src/components/editor-page/renderer-pane/render-iframe.tsx
  src/components/render-page/window-post-message-communicator/rendering-message.ts
  src/utils/cypress-attribute.ts
Labels: type: bug

#1650 use useInterval hook in ui-notification-toast
  src/components/notifications/ui-notification-toast.tsx
Labels: type: code quality enhancement

#1652 Remove useMemo from interval
  src/components/notifications/ui-notification-toast.tsx
Labels: type: code quality enhancement

#1649 Deduplicate CommonModal Props
  src/components/common/modals/common-modal.tsx
  src/components/common/modals/deletion-modal.tsx
  src/components/common/motd-modal/motd-modal.tsx
  src/components/editor-page/app-bar/help-button/cheatsheet-tab-content.tsx
  src/components/editor-page/app-bar/help-button/help-modal.tsx
  src/components/editor-page/app-bar/help-button/links-tab-content.tsx
  src/components/editor-page/app-bar/help-button/shortcuts-tab-content.tsx
  src/components/editor-page/document-bar/document-info/document-info-modal.tsx
  src/components/editor-page/document-bar/permissions/permission-modal.tsx
  src/components/editor-page/document-bar/revisions/revision-modal.tsx
  src/components/editor-page/document-bar/share/share-modal.tsx
  src/components/editor-page/editor-modals/max-length-warning-modal.tsx
  src/components/editor-page/editor-pane/tool-bar/editor-preferences/editor-preferences.tsx
  src/components/editor-page/editor-pane/tool-bar/table-picker/custom-table-size-modal.tsx
  src/components/editor-page/sidebar/delete-note-sidebar-entry.tsx
  src/components/history-page/entry-menu/dropdown-item-with-deletion-modal.tsx
  src/components/history-page/history-toolbar/clear-history-button.tsx
  src/components/landing-layout/footer/version-info/version-info-modal.tsx
  src/components/markdown-renderer/markdown-extension/image/image-lightbox-modal.tsx
  src/components/profile-page/access-tokens/profile-access-tokens.tsx
Labels: type: code quality enhancement

#1654 Restructure the max-length-warning and the status bar
  src/components/editor-page/editor-pane/editor-pane.tsx
  src/components/editor-page/editor-pane/hooks/use-create-status-bar-info.ts
  src/components/editor-page/editor-pane/max-length-warning/max-length-warning-modal.tsx
  src/components/editor-page/editor-pane/max-length-warning/max-length-warning.tsx
  src/components/editor-page/editor-pane/status-bar/cursor-position-info.tsx
  src/components/editor-page/editor-pane/status-bar/number-of-lines-in-document-info.tsx
  src/components/editor-page/editor-pane/status-bar/remaining-characters-info.tsx
  src/components/editor-page/editor-pane/status-bar/selection-info.tsx
  src/components/editor-page/editor-pane/status-bar/separator-dash.tsx
  src/components/editor-page/editor-pane/status-bar/status-bar.tsx
Labels: type: code quality enhancement
