Repository hedgedoc/react-client, pull requests merged in 2021-04, with the labels that each got.

#1145 Change mailmap entry for "Tilman Vatteroth"
  .mailmap
Labels: priority: 3 low

#1146 Add context for iframe communicator in editor page
  src/components/editor-page/editor-page.tsx
  src/components/editor-page/render-context/iframe-communicator-context-provider.tsx
  src/components/editor-page/renderer-pane/render-iframe.tsx
Labels: priority: 1 high, scope: editor, type: feature enhancement

#1159 Add renovate group for vega lite
  renovate.json
Labels: type: code quality enhancement

#1160 Revert "Update dependency d3-graphviz to v4"
  package.json
  yarn.lock
Labels: type: maintenance

#1178 Improve renovate config by adding new groups
  renovate.json
Labels: type: code quality enhancement

#1184 Change plantuml server url to https
  public/api/v2/config
Labels: scope: renderer, type: feature enhancement

#1186 Disallow data and javascript URIs
  cypress/integration/linkSchemes.ts
  src/components/markdown-renderer/replace-components/link-replacer/link-replacer.tsx
Labels: scope: renderer, type: feature enhancement

#1187 Remove browserstack integration
  .github/workflows/e2e.yml
  browserstack.json
  browserstack.json.license
  package.json
  yarn.lock
Labels: priority: 1 high, type: maintenance

#1190 Update dependencies
  package.json
  yarn.lock
Labels: type: maintenance

#1189 Change api route to /api/private
  cypress/integration/fileUpload.spec.ts
  cypress/integration/history.spec.ts
  cypress/integration/profile.spec.ts
  cypress/integration/signInButton.spec.ts
  cypress/support/config.ts
  cypress/support/visit-test-editor.ts
  public/api/private/config
  public/api/private/history
  public/api/private/me
  public/api/private/notes/banner
  public/api/private/notes/features-get
  public/api/private/notes/features/revisions-list
  public/api/private/notes/features/revisions/1598389571
  public/api/private/notes/features/revisions/1598390307
  public/api/private/notes/old
  public/api/private/tokens
  public/api/private/users/dermolly
  public/api/private/users/emcrx
  public/api/private/users/mrdrogdrog
  src/components/application-loader/initializers/configLoader.ts
Labels: status: ready to merge

#1191 Fix code highlight indentation
  src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-code/highlighted-code.scss
Labels: priority: 2 medium, scope: renderer, type: bug

#1192 Use module build of markmap-lib
  package.json
  src/components/markdown-renderer/replace-components/markmap/markmap-loader.ts
  src/external-types/markmap-lib/index.d.ts
  yarn.lock
Labels: priority: 2 medium, scope: renderer, type: bug

#1202 TablePicker: Change table cells in picker
  src/components/editor-page/editor-pane/tool-bar/table-picker/table-picker.scss
  src/components/editor-page/editor-pane/tool-bar/table-picker/table-picker.tsx
Labels: scope: UI/UX, status: ready to merge, type: feature enhancement

#1156 The History PR: I - Move to redux
  cypress/integration/history.spec.ts
  public/api/private/history
  src/api/history/dto-methods.ts
  src/api/history/index.ts
  src/api/history/types.d.ts
  src/components/application-loader/initializers/index.ts
  src/components/history-page/entry-menu/entry-menu.tsx
  src/components/history-page/history-card/history-card-list.tsx
  src/components/history-page/history-card/history-card.tsx
  src/components/history-page/history-content/history-content.tsx
  src/components/history-page/history-page.tsx
  src/components/history-page/history-table/history-table-row.tsx
  src/components/history-page/history-table/history-table.tsx
  src/components/history-page/history-toolbar/clear-history-button.tsx
  src/components/history-page/history-toolbar/export-history-button.tsx
  src/components/history-page/history-toolbar/history-toolbar.tsx
  src/components/history-page/history-toolbar/import-history-button.tsx
  src/components/history-page/utils.ts
  src/redux/history/methods.ts
  src/redux/history/reducers.ts
  src/redux/history/types.ts
  src/redux/index.ts
  src/redux/ui-notifications/methods.ts
  tsconfig.json
Labels: scope: history, type: code quality enhancement

#1157 The History PR: II - Add URL params
  CHANGELOG.md
  package.json
  src/components/history-page/history-page.tsx
  src/components/history-page/history-toolbar/history-toolbar.tsx
  yarn.lock
Labels: scope: history, type: feature enhancement
