Repository hedgedoc/react-client, pull requests merged in 2021-06, with the labels that each got.

#1293 Replace emojibase-data with emoji-picker-element-data
  craco.config.js
  package.json
  src/components/markdown-renderer/markdown-it-plugins/emoji/mapping.ts
  src/style/fonts/twemoji/TwemojiMozilla.ttf
  yarn.lock
Labels: type: feature enhancement

#1295 Replace deprecated highlight.js syntax
  src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-code/highlighted-code.tsx
Labels: type: code quality enhancement

#1304 Replace twemoji files with twemoji npm package
  package.json
  src/components/editor-page/editor-pane/editor-pane.scss
  src/components/editor-page/editor-pane/tool-bar/emoji-picker/emoji-picker.tsx
  src/components/markdown-renderer/markdown-renderer.scss
  src/components/markdown-renderer/replace-components/flow/flowchart/flowchart.tsx
  src/style/fonts/twemoji/TwemojiMozilla.ttf
  src/style/fonts/twemoji/TwemojiMozilla.ttf.license
  src/style/fonts/twemoji/twemoji.scss
  src/style/index.scss
  src/style/variables.scss
  yarn.lock
Labels: type: feature enhancement

#1302 Extract toc button
  src/components/editor-page/document-renderer-pane/hooks/use-adapted-line-markers-callback.ts
  src/components/editor-page/document-renderer-pane/hooks/use-on-iframe-load.ts
  src/components/editor-page/document-renderer-pane/show-on-prop-change-image-lightbox.tsx
  src/components/editor-page/editor-pane/editor-pane.tsx
  src/components/editor-page/table-of-contents/table-of-contents.scss
  src/components/intro-page/intro-page.tsx
  src/components/render-page/markdown-document.tsx
  src/components/render-page/markdown-toc-button/markdown-toc-button.scss
  src/components/render-page/markdown-toc-button/table-of-contents-hovering-button.tsx
  src/components/render-page/width-based-table-of-contents.tsx
Labels: type: code quality enhancement

#1308 Add application state hook (1/3)
  src/components/common/branding/branding.tsx
  src/components/common/motd-banner/motd-banner.tsx
  src/components/document-read-only-page/document-read-only-page.tsx
  src/components/editor-page/app-bar/app-bar.tsx
  src/components/editor-page/app-bar/editor-view-mode.tsx
  src/components/editor-page/app-bar/sync-scroll-buttons/sync-scroll-buttons.tsx
  src/components/editor-page/document-bar/share/share-modal.tsx
  src/components/editor-page/editor-page.tsx
  src/components/editor-page/editor-pane/editor-pane.tsx
  src/components/editor-page/editor-pane/tool-bar/editor-preferences/editor-preference-boolean-property.tsx
  src/components/editor-page/editor-pane/tool-bar/editor-preferences/editor-preference-ligatures-select.tsx
  src/components/editor-page/editor-pane/tool-bar/editor-preferences/editor-preference-number-property.tsx
  src/components/editor-page/editor-pane/tool-bar/editor-preferences/editor-preference-select-property.tsx
  src/components/editor-page/editor-pane/tool-bar/editor-preferences/editor-preference-smart-paste-select.tsx
  src/components/editor-page/editor-pane/tool-bar/editor-preferences/editor-preferences.tsx
  src/components/editor-page/hooks/useUpdateLocalHistoryEntry.ts
  src/components/editor-page/renderer-pane/render-iframe.tsx
  src/components/editor-page/renderer-pane/yaml-array-deprecation-alert.tsx
  src/components/editor-page/sidebar/pin-note-sidebar-entry.tsx
  src/components/history-page/entry-menu/entry-menu.tsx
  src/components/history-page/history-page.tsx
  src/components/history-page/history-toolbar/history-toolbar.tsx
  src/components/history-page/history-toolbar/import-history-button.tsx
  src/components/intro-page/cover-buttons/cover-buttons.tsx
  src/components/landing-layout/footer/powered-by-links.tsx
  src/components/landing-layout/footer/version-info/version-info-modal.tsx
  src/components/landing-layout/navigation/header-bar/header-bar.tsx
  src/components/landing-layout/navigation/sign-in-button.tsx
  src/components/landing-layout/navigation/user-dropdown.tsx
  src/components/login-page/auth/via-internal.tsx
  src/components/login-page/auth/via-ldap.tsx
  src/components/login-page/auth/via-one-click.tsx
  src/components/login-page/login-page.tsx
  src/components/markdown-renderer/document-length-limit-reached-alert.tsx
  src/components/markdown-renderer/hooks/use-trimmed-content.ts
  src/components/markdown-renderer/replace-components/image/proxy-image-frame.tsx
  src/components/notifications/ui-notifications.tsx
  src/components/profile-page/profile-page.tsx
  src/components/profile-page/settings/profile-display-name.tsx
  src/components/register-page/register-page.tsx
  src/components/render-page/markdown-document.tsx
  src/components/render-page/render-page.tsx
  src/hooks/common/use-application-state.ts
  src/hooks/common/use-document-title-with-note-title.ts
  src/hooks/common/use-document-title.ts
  src/hooks/common/use-is-dark-mode-activated.ts
  src/hooks/common/use-note-markdown-content.ts
Labels: type: code quality enhancement

#1310 Iframe communicator context (2/3)
  src/components/editor-page/editor-page.tsx
  src/components/editor-page/editor-pane/editor-pane.tsx
  src/components/editor-page/render-context/iframe-editor-to-renderer-communicator-context-provider.tsx
  src/components/editor-page/render-context/iframe-renderer-to-editor-communicator-context-provider.tsx
  src/components/editor-page/renderer-pane/hooks/use-on-iframe-load.ts
  src/components/editor-page/renderer-pane/render-iframe.tsx
  src/components/intro-page/intro-page.tsx
  src/components/render-page/hooks/use-image-click-handler.ts
  src/components/render-page/iframe-markdown-renderer.tsx
  src/components/render-page/render-page.tsx
Labels: type: code quality enhancement

#1307 Fix splitter
  src/components/editor-page/editor-page.tsx
  src/components/editor-page/splitter/splitter.scss
  src/components/editor-page/splitter/splitter.tsx
  src/components/markdown-renderer/markdown-renderer.scss
  src/components/markdown-renderer/replace-components/abc/abc-frame.tsx
  src/components/markdown-renderer/replace-components/graphviz/graphviz-frame.tsx
  src/components/markdown-renderer/replace-components/markmap/markmap-frame.tsx
  src/redux/note-details/methods.ts
Labels: type: bug

#1318 Remove unused licenses
  LICENSES/BSD-3-Clause.txt
  LICENSES/CC-BY-4.0.txt
Labels: type: code quality enhancement

#1319 Improve stability and speed of E2E tests
  .github/workflows/e2e.yml
  public/locales/en.json
  src/components/editor-page/editor-pane/autocompletion/code-block.ts
  src/components/editor-page/editor-pane/autocompletion/header.ts
  src/components/editor-page/editor-pane/autocompletion/index.ts
  src/components/notifications/ui-notification-toast.tsx
Labels: type: feature enhancement

#1322 Add extra test suite for emojis
  cypress/integration/autocompletion.spec.ts
  cypress/integration/emoji.spec.ts
Labels: type: feature enhancement

#738 Add word count in document info modal
  CHANGELOG.md
  cypress/integration/word-count.spec.ts
  package.json
  public/locales/en.json
  src/components/editor-page/document-bar/document-info/document-info-line-word-count.tsx
  src/components/editor-page/document-bar/document-info/document-info-modal.tsx
  src/components/editor-page/document-bar/document-info/unitalic-bold-text.tsx
  src/components/editor-page/sidebar/document-info-sidebar-entry.tsx
  src/components/render-page/iframe-editor-to-renderer-communicator.ts
  src/components/render-page/iframe-markdown-renderer.tsx
  src/components/render-page/iframe-renderer-to-editor-communicator.ts
  src/components/render-page/rendering-message.ts
  src/components/render-page/word-counter.ts
  src/external-types/words-count/words-count.d.ts
  yarn.lock
Labels: priority: 2 medium, scope: editor, type: feature

#1328 Throw error if no communicator was found in a react context
  src/components/editor-page/render-context/iframe-editor-to-renderer-communicator-context-provider.tsx
  src/components/editor-page/render-context/iframe-renderer-to-editor-communicator-context-provider.tsx
  src/components/editor-page/renderer-pane/hooks/use-on-iframe-load.ts
  src/components/editor-page/renderer-pane/render-iframe.tsx
  src/components/render-page/hooks/use-image-click-handler.ts
  src/components/render-page/iframe-markdown-renderer.tsx
Labels: scope: editor, scope: renderer

#1329 Fix unique key in ui-notification-toast
  src/components/notifications/ui-notification-toast.tsx
Labels: type: bug

#1327 Replace react-html-parser with html-to-react
  cypress/integration/autocompletion.spec.ts
  cypress/integration/emoji.spec.ts
  cypress/support/getMarkdownRenderer.ts
  package.json
  src/components/markdown-renderer/basic-markdown-renderer.tsx
  src/components/markdown-renderer/hooks/use-component-replacers.ts
  src/components/markdown-renderer/hooks/use-convert-markdown-to-react-dom.ts
  src/components/markdown-renderer/replace-components/ComponentReplacer.ts
  src/components/markdown-renderer/replace-components/abc/abc-replacer.tsx
  src/components/markdown-renderer/replace-components/asciinema/asciinema-replacer.tsx
  src/components/markdown-renderer/replace-components/colored-blockquote/colored-blockquote-replacer.tsx
  src/components/markdown-renderer/replace-components/csv/csv-replacer.tsx
  src/components/markdown-renderer/replace-components/flow/flowchart-replacer.tsx
  src/components/markdown-renderer/replace-components/gist/gist-replacer.tsx
  src/components/markdown-renderer/replace-components/graphviz/graphviz-replacer.tsx
  src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-code/highlighted-code.tsx
  src/components/markdown-renderer/replace-components/highlighted-fence/highlighted-fence-replacer.tsx
  src/components/markdown-renderer/replace-components/image/image-replacer.tsx
  src/components/markdown-renderer/replace-components/katex/katex-replacer.tsx
  src/components/markdown-renderer/replace-components/linemarker/linemarker-replacer.tsx
  src/components/markdown-renderer/replace-components/link-replacer/link-replacer.tsx
  src/components/markdown-renderer/replace-components/markmap/markmap-replacer.tsx
  src/components/markdown-renderer/replace-components/mermaid/mermaid-replacer.tsx
  src/components/markdown-renderer/replace-components/sequence-diagram/sequence-diagram-replacer.tsx
  src/components/markdown-renderer/replace-components/task-list/task-list-replacer.tsx
  src/components/markdown-renderer/replace-components/utils.ts
  src/components/markdown-renderer/replace-components/vega-lite/vega-replacer.tsx
  src/components/markdown-renderer/replace-components/vimeo/vimeo-replacer.tsx
  src/components/markdown-renderer/replace-components/youtube/youtube-replacer.tsx
  src/components/markdown-renderer/utils/html-react-transformer.tsx
  yarn.lock
Labels: type: maintenance

#1330 Add renderer ready state to global application state
  src/components/editor-page/document-bar/document-info/document-info-line-word-count.tsx
  src/components/editor-page/render-context/iframe-renderer-to-editor-communicator-context-provider.tsx
  src/components/editor-page/renderer-pane/hooks/use-on-iframe-load.ts
  src/components/editor-page/renderer-pane/render-iframe.tsx
  src/components/intro-page/intro-page.tsx
  src/components/render-page/iframe-communicator.ts
  src/components/render-page/iframe-editor-to-renderer-communicator.ts
  src/components/render-page/iframe-markdown-renderer.tsx
  src/components/render-page/iframe-renderer-to-editor-communicator.ts
  src/redux/editor/methods.ts
  src/redux/editor/reducers.ts
  src/redux/editor/types.ts
Labels: type: bug

#1337 Add new data property to iframe that indicates if the content is ready.
  cypress/support/getMarkdownRenderer.ts
  src/components/editor-page/renderer-pane/render-iframe.tsx
Labels: type: bug

#1344 Extract render ready status
  src/components/editor-page/document-bar/document-info/document-info-line-word-count.tsx
  src/components/editor-page/renderer-pane/render-iframe.tsx
  src/components/intro-page/intro-page.tsx
  src/redux/editor/methods.ts
  src/redux/editor/reducers.ts
  src/redux/editor/types.ts
  src/redux/index.ts
  src/redux/renderer-status/methods.ts
  src/redux/renderer-status/reducers.ts
  src/redux/renderer-status/types.ts
Labels: priority: 0 critical, type: bug

#1343 Add useCappedRelativeSplitValue
  cypress/integration/splitter.spec.ts
  src/components/editor-page/app-bar/editor-view-mode.tsx
  src/components/editor-page/splitter/hooks/use-adjusted-relative-split-value.ts
  src/components/editor-page/splitter/splitter.tsx
Labels: scope: editor, type: bug

#1345 Fix context error in view only
  src/components/document-read-only-page/document-read-only-page.tsx
Labels: priority: 0 critical, type: bug

#1356 Add codestyle docs
  CONTRIBUTING.md
Labels: type: documentation
