Repository hedgedoc/react-client, pull requests merged in 2021-03, with the labels that each got.

#1085 Extract code into hook
  src/components/editor-page/editor-page.tsx
  src/components/editor-page/hooks/useEditorModeFromUrl.ts
Labels: priority: 3 low, scope: editor, type: code quality enhancement

#1043 Add one-click login if possible
  CHANGELOG.md
  cypress/integration/autocompletion.spec.ts
  cypress/integration/banner.spec.ts
  cypress/integration/diagrams.spec.ts
  cypress/integration/documentTitle.spec.ts
  cypress/integration/editorMode.spec.ts
  cypress/integration/export.spec.ts
  cypress/integration/fileUpload.spec.ts
  cypress/integration/helpDialog.spec.ts
  cypress/integration/highlightedCodeBlock.spec.ts
  cypress/integration/history.spec.ts
  cypress/integration/import.spec.ts
  cypress/integration/intro.spec.ts
  cypress/integration/language.spec.ts
  cypress/integration/link.spec.ts
  cypress/integration/linkEmbedder.spec.ts
  cypress/integration/maxLength.spec.ts
  cypress/integration/profile.spec.ts
  cypress/integration/quote-extra.spec.ts
  cypress/integration/shortcodes.spec.ts
  cypress/integration/signInButton.spec.ts
  cypress/integration/toolbar.spec.ts
  cypress/integration/yamlArrayDeprecationMessage.spec.ts
  cypress/support/config.ts
  src/api/auth/index.ts
  src/components/landing-layout/navigation/sign-in-button.tsx
Labels: type: feature enhancement

#1089 Replace acme.png with demo.png
  cypress/fixtures/acme.png
  cypress/fixtures/demo.png
  cypress/fixtures/demo.png.license
  cypress/integration/fileUpload.spec.ts
  cypress/support/config.ts
  public/api/v2/config
  public/img/acme.png
  public/img/demo.png
  public/img/demo.png.license
Labels: priority: 3 low

#957 Add table formatting on paste of detected table
  CHANGELOG.md
  cypress/integration/fileUpload.spec.ts
  public/locales/en.json
  src/components/editor-page/editor-pane/editor-pane.tsx
  src/components/editor-page/editor-pane/table-extractor.test.ts
  src/components/editor-page/editor-pane/table-extractor.ts
  src/components/editor-page/editor-pane/tool-bar/editor-preferences/editor-preference-smart-paste-select.tsx
  src/components/editor-page/editor-pane/tool-bar/editor-preferences/editor-preferences.tsx
  src/components/editor-page/editor-pane/tool-bar/utils/codefenceDetection.test.ts
  src/components/editor-page/editor-pane/tool-bar/utils/codefenceDetection.ts
  src/components/editor-page/editor-pane/tool-bar/utils/pasteHandlers.ts
  src/redux/editor/methods.ts
  src/redux/editor/reducers.ts
  src/redux/editor/types.ts
Labels: scope: editor, type: feature

#1073 Notifications
  src/components/editor-page/editor-page.tsx
  src/components/editor-page/use-notification-test.tsx
  src/components/landing-layout/landing-layout.tsx
  src/components/notifications/notifications.scss
  src/components/notifications/ui-notification-toast.tsx
  src/components/notifications/ui-notifications.tsx
  src/redux/index.ts
  src/redux/ui-notifications/methods.ts
  src/redux/ui-notifications/reducers.ts
  src/redux/ui-notifications/types.ts
  src/style/variables.light.scss
Labels: priority: 2 medium, type: feature

#1111 Add symlink for LICENSE
  LICENSE
Labels: priority: 3 low, type: documentation

#1130 Change type of LICENSE
  LICENSE
Labels: priority: 3 low, type: documentation
