Repository hedgedoc/react-client, pull requests merged in 2022-11, with the labels that each got.

#2452 fix(ci): run workflows in target repository context
  .github/workflows/build.yml
  .github/workflows/deploy-main.yml
  .github/workflows/deploy-pr.yml
  .github/workflows/e2e.yml
  .github/workflows/lint.yml
  .github/workflows/reuse.yml
  netlify/deploy-main.sh
  netlify/deploy-pr.sh
  netlify/netlify-cli.sh
  netlify/patch-files.sh
  renovate.json
Labels: type: ci/cd, FORCE DEPLOY

#2483 fix(ci): fix regex manager name for node version
  renovate.json
Labels: type: ci/cd

#2484 Fix deployment workflow
  .github/workflows/deploy-pr.yml
Labels: type: ci/cd

#2069 test: common modals
  src/components/common/modals/__snapshots__/common-modal.test.tsx.snap
  src/components/common/modals/__snapshots__/deletion-moadal.test.tsx.snap
  src/components/common/modals/common-modal.test.tsx
  src/components/common/modals/common-modal.tsx
  src/components/common/modals/deletion-moadal.test.tsx
Labels: type: code quality enhancement

#2505 feat: add codeql workflow
  .github/workflows/codeql.yml
Labels: type: ci/cd

#2521 Settings dialog
  cypress/e2e/language.spec.ts
  locales/en.json
  src/components/application-loader/initializers/load-dark-mode.ts
  src/components/common/icon-button/icon-button.tsx
  src/components/editor-page/app-bar/app-bar.tsx
  src/components/editor-page/app-bar/dark-mode-button.tsx
  src/components/editor-page/app-bar/navbar-branding.tsx
  src/components/editor-page/app-bar/sync-scroll-buttons/buttonIcon.inkscape.svg
  src/components/editor-page/app-bar/sync-scroll-buttons/disabledScroll.svg
  src/components/editor-page/app-bar/sync-scroll-buttons/enabledScroll.svg
  src/components/editor-page/app-bar/sync-scroll-buttons/sync-scroll-buttons.module.scss
  src/components/editor-page/app-bar/sync-scroll-buttons/sync-scroll-buttons.tsx
  src/components/editor-page/document-bar/revisions/revision-viewer.tsx
  src/components/editor-page/editor-pane/editor-pane.tsx
  src/components/editor-page/editor-pane/linter/linter.ts
  src/components/editor-page/editor-pane/tool-bar/emoji-picker/emoji-picker-popover.tsx
  src/components/editor-page/renderer-pane/hooks/use-send-dark-mode-status-to-renderer.ts
  src/components/landing-layout/footer/footer.tsx
  src/components/landing-layout/navigation/header-bar/header-bar.tsx
  src/components/layout/settings-dialog/editor/editor-settings-tab-content.tsx
  src/components/layout/settings-dialog/editor/ligature-setting-button-group.tsx
  src/components/layout/settings-dialog/editor/smart-paste-setting-button-group.tsx
  src/components/layout/settings-dialog/editor/sync-scroll-setting-button-group.tsx
  src/components/layout/settings-dialog/global/dark-mode-setting-button-group.tsx
  src/components/layout/settings-dialog/global/global-settings-tab-content.tsx
  src/components/layout/settings-dialog/global/language-picker.tsx
  src/components/layout/settings-dialog/settings-button.tsx
  src/components/layout/settings-dialog/settings-modal.tsx
  src/components/layout/settings-dialog/utils/__snapshots__/on-off-button-group.test.tsx.snap
  src/components/layout/settings-dialog/utils/on-off-button-group.test.tsx
  src/components/layout/settings-dialog/utils/on-off-button-group.tsx
  src/components/layout/settings-dialog/utils/setting-line.tsx
  src/components/layout/settings-dialog/utils/settings-toggle-button.tsx
  src/components/render-page/iframe-markdown-renderer.tsx
  src/components/render-page/window-post-message-communicator/rendering-message.ts
  src/extensions/extra-integrations/flowchart/flowchart.test.tsx
  src/extensions/extra-integrations/flowchart/flowchart.tsx
  src/hooks/common/use-apply-dark-mode.ts
  src/hooks/common/use-dark-mode-state.ts
  src/hooks/common/use-is-dark-mode-activated.ts
  src/redux/dark-mode/methods.ts
  src/redux/dark-mode/reducers.ts
  src/redux/dark-mode/types.ts
  src/utils/cypress-attribute.ts
  src/utils/test-id.ts
Labels: type: feature

#2529 Disable renovate
  renovate.json
Labels: type: maintenance
