Repository hedgedoc/react-client, pull requests merged in 2022-01, with the labels that each got.

#1744 Don't upload cache to build artifact
  .github/workflows/e2e.yml
Labels: type: feature enhancement

#1745 Use yarn berry install command in cypress action
  .github/workflows/e2e.yml
Labels: type: code quality enhancement

#1746 Add basic meta tags
  public/index.html
  src/components/landing-layout/landing-layout.tsx
  src/components/layout/base-head.tsx
  src/components/layout/fav-icon.tsx
  src/components/layout/note-and-app-title-head.tsx
  src/hooks/common/use-app-title.ts
  src/hooks/common/use-note-title.ts
  src/pages/_app.tsx
  src/pages/n/[id].tsx
  src/pages/p/[id].tsx
  src/pages/s/[id].tsx
Labels: type: bug

#1733 fix: add translation for app logo title
  locales/en.json
  src/components/application-loader/application-loader.module.scss
  src/components/application-loader/application-loader.tsx
  src/components/application-loader/initializers/fetch-motd.ts
  src/components/application-loader/loading-screen/animated-hedge-doc-logo/animated-hedge-doc-logo.tsx
  src/components/application-loader/loading-screen/animated-hedge-doc-logo/animations.module.scss
  src/components/application-loader/loading-screen/loading-screen.tsx
  src/components/common/hedge-doc-logo/hedge-doc-logo-with-text.tsx
  src/components/common/hedge-doc-logo/hedge-doc-logo.tsx
  src/pages/n/[id].tsx
Labels: type: feature enhancement

#1748 Reduce number of e2e containers to 5
  .github/workflows/e2e.yml
Labels: type: code quality enhancement

#1752 Add condition to modal
  src/components/common/modals/common-modal.tsx
Labels: type: code quality enhancement

#1769 Fix changelog faq
  CHANGELOG.md
Labels: type: documentation

#1784 Add plantuml not configured tag to tag name whiteliste
  src/components/markdown-renderer/markdown-extension/plantuml/plantuml-markdown-extension.ts
Labels: type: bug

#1800 Add netlify deployments for PRs
  .github/workflows/deploy.yml
  .gitignore
  .netlify/state.json
  .reuse/dep5
  netlify.toml
  netlify/deploy.sh
  package.json
  yarn.lock
Labels: type: ci/cd

#1801 deployments: Fix main branch deployment and overrides
  .github/workflows/deploy.yml
  netlify.toml
  netlify/build.sh
  netlify/deploy.sh
Labels: type: ci/cd

#1819 Fix netlify not using aliases containing a slash
  .github/workflows/deploy.yml
  netlify/deploy.sh
Labels: type: ci/cd

#1820 Add new visit functions in e2e tests
  cypress/integration/autocompletion.spec.ts
  cypress/integration/deleteNote.spec.ts
  cypress/integration/diagrams.spec.ts
  cypress/integration/document-read-only-page.spec.ts
  cypress/integration/documentTitle.spec.ts
  cypress/integration/editorMode.spec.ts
  cypress/integration/emoji.spec.ts
  cypress/integration/export.spec.ts
  cypress/integration/fileUpload.spec.ts
  cypress/integration/helpDialog.spec.ts
  cypress/integration/highlightedCodeBlock.spec.ts
  cypress/integration/history.spec.ts
  cypress/integration/iframe-capsule.ts
  cypress/integration/import.spec.ts
  cypress/integration/intro.spec.ts
  cypress/integration/language.spec.ts
  cypress/integration/link.spec.ts
  cypress/integration/linkEmbedder.spec.ts
  cypress/integration/linkSchemes.spec.ts
  cypress/integration/maxLength.spec.ts
  cypress/integration/motd.spec.ts
  cypress/integration/profile.spec.ts
  cypress/integration/quote-extra.spec.ts
  cypress/integration/renderer-mode.spec.ts
  cypress/integration/shortcodes.spec.ts
  cypress/integration/signInButton.spec.ts
  cypress/integration/slideshow-only-page.spec.ts
  cypress/integration/splitter.spec.ts
  cypress/integration/taskLists.spec.ts
  cypress/integration/word-count.spec.ts
  cypress/integration/yamlArrayDeprecationMessage.spec.ts
  cypress/support/index.ts
  cypress/support/visit-test-editor.ts
  cypress/support/visit.ts
Labels: type: feature enhancement
