Repository hedgedoc/react-client, pull requests merged in 2022-05, with the labels that each got.

#2023 Create store using redux-toolkit
  package.json
  src/redux/index.ts
  yarn.lock
Labels: type: maintenance

#1998 New note creation
  CHANGELOG.md
  locales/en.json
  src/components/common/async-loading-boundary.tsx
  src/components/common/routing/not-found-error-screen.tsx
  src/components/editor-page/app-bar/new-note-button.tsx
  src/components/error-pages/common-error-page.tsx
  src/pages/404.tsx
  src/pages/[id].tsx
  src/pages/api/mock-backend/private/notes/index.ts
  src/pages/new.tsx
Labels: type: feature

#2025 Extract code highlighting from async call
  src/components/markdown-renderer/markdown-extension/highlighted-fence/highlighted-code.tsx
  src/components/markdown-renderer/markdown-extension/highlighted-fence/hooks/use-async-highlight-js-import.tsx
  src/components/markdown-renderer/markdown-extension/highlighted-fence/hooks/use-code-dom.tsx
Labels: type: bug, status: ready to merge

#2064 Remove flaky intro links test
  cypress/integration/link.spec.ts
Labels: type: code quality enhancement
