Repository hedgedoc/react-client, pull requests merged in 2022-07, with the labels that each got.

#2154 feat: switch editor and render view buttons
  src/components/editor-page/app-bar/editor-view-mode.tsx
Labels: scope: UI/UX

#2155 fix(notification): set position of notification-area to fixed
  src/components/notifications/notifications.module.scss
Labels: type: bug

#2174 Add mutation observer to first heading title extraction logic
  cypress/e2e/documentTitle.spec.ts
  src/components/markdown-renderer/hooks/use-extract-first-headline.ts
Labels: type: bug

#2178 Use window location as base url for websocket url construction
  src/components/editor-page/editor-pane/hooks/yjs/use-websocket-url.ts
Labels: type: bug

#2173 Add button to create note if not found
  locales/en.json
  src/api/notes/index.ts
  src/components/common/note-loading-boundary/__snapshots__/create-non-existing-note-hint.test.tsx.snap
  src/components/common/note-loading-boundary/__snapshots__/note-loading-boundary.test.tsx.snap
  src/components/common/note-loading-boundary/create-non-existing-note-hint.test.tsx
  src/components/common/note-loading-boundary/create-non-existing-note-hint.tsx
  src/components/common/note-loading-boundary/note-loading-boundary.test.tsx
  src/components/common/note-loading-boundary/note-loading-boundary.tsx
  src/components/common/redirect.tsx
  src/components/error-pages/common-error-page.tsx
  src/pages/[id].tsx
Labels: type: feature

#2170 Add eslint-plugin-prettier
  .eslintrc.json
  .github/workflows/lint.yml
  package.json
  yarn.lock
Labels: type: code quality enhancement

#2183 Remove redux devtools package
  package.json
  yarn.lock
Labels: type: maintenance

#2184 Fix splitter tests
  src/components/editor-page/splitter/__snapshots__/splitter.test.tsx.snap
  src/components/editor-page/splitter/splitter.test.tsx
  src/components/editor-page/splitter/splitter.tsx
Labels: type: bug

#2186 Add modal visibility state hook
  src/components/editor-page/app-bar/help-button/help-button.tsx
  src/components/editor-page/editor-pane/max-length-warning/max-length-warning.tsx
  src/components/editor-page/renderer-pane/communicator-image-lightbox.tsx
  src/components/editor-page/sidebar/delete-note-sidebar-entry/delete-note-sidebar-entry.tsx
  src/components/editor-page/sidebar/specific-sidebar-entries/note-info-sidebar-entry.tsx
  src/components/editor-page/sidebar/specific-sidebar-entries/permissions-sidebar-entry.tsx
  src/components/editor-page/sidebar/specific-sidebar-entries/revision-sidebar-entry.tsx
  src/components/editor-page/sidebar/specific-sidebar-entries/share-sidebar-entry.tsx
  src/components/history-page/entry-menu/dropdown-item-with-deletion-modal.tsx
  src/components/history-page/history-toolbar/clear-history-button.tsx
  src/components/landing-layout/footer/version-info/version-info-link.tsx
  src/components/profile-page/access-tokens/access-token-deletion-modal.tsx
  src/components/profile-page/access-tokens/access-token-list-entry.tsx
  src/components/profile-page/account-management/profile-account-management.tsx
  src/hooks/common/use-boolean-state.ts
Labels: status: ready to merge, type: code quality enhancement

#2229 Remove non-existing css class reference in splitter
  src/components/editor-page/splitter/__snapshots__/splitter.test.tsx.snap
  src/components/editor-page/splitter/splitter.tsx
Labels: type: bug

#2240 Update cypress browser image to node16.14.2-slim-chrome103-ff102
  .github/workflows/e2e.yml
Labels: type: maintenance

#2252 Use yarn pnp as module linker
  .github/workflows/build.yml
  .github/workflows/e2e.yml
  .yarnrc.yml
  Dockerfile
  README.md
  cypress.config.js
  cypress.config.ts
  cypress/tsconfig.json
  jest.config.ts
  netlify/deploy-main.sh
  netlify/deploy-pr.sh
  netlify/netlify-cli.sh
  next.config.js
  package.json
  renovate.json
  tsconfig.json
  yarn.lock
Labels: type: maintenance

#2258 Fix parameters in netlify cli script
  .github/workflows/deploy-main.yml
  .github/workflows/deploy-pr.yml
  netlify/deploy-main.sh
  netlify/deploy-pr.sh
  netlify/netlify-cli.sh
  netlify/patch-files.sh
  package.json
Labels: type: bug, priority: 0 critical

#2239 Remove roman line numbers
  global-styles/github-markdown.scss
Labels: scope: renderer, priority: 3 low

#2242 Add memorized hook for table of contents
  src/components/editor-page/table-of-contents/__snapshots__/table-of-contents.test.tsx.snap
  src/components/editor-page/table-of-contents/table-of-contents.test.tsx
  src/components/editor-page/table-of-contents/table-of-contents.tsx
  src/components/editor-page/table-of-contents/use-build-react-dom-from-toc-ast.tsx
Labels: type: code quality enhancement, priority: 3 low

#2241 Fixes warnings in some tests
  src/components/common/copyable/copy-to-clipboard-button/copy-to-clipboard-button.test.tsx
  src/components/common/note-loading-boundary/__snapshots__/create-non-existing-note-hint.test.tsx.snap
  src/components/common/note-loading-boundary/create-non-existing-note-hint.test.tsx
  src/components/common/note-loading-boundary/create-non-existing-note-hint.tsx
  src/components/common/user-avatar/user-avatar.test.tsx
  src/utils/wait-for-other-promises-to-finish.ts
Labels: type: code quality enhancement, priority: 3 low

#2260 Enable push of docker images
  .github/workflows/docker.yml
Labels: type: ci/cd

#2237 feat: add linter and linterGutter
  cypress/e2e/yamlArrayDeprecationMessage.spec.ts
  locales/en.json
  package.json
  src/components/editor-page/editor-pane/editor-pane.tsx
  src/components/editor-page/editor-pane/extended-codemirror/codemirror.module.scss
  src/components/editor-page/editor-pane/linter/frontmatter-linter.spec.ts
  src/components/editor-page/editor-pane/linter/frontmatter-linter.ts
  src/components/editor-page/editor-pane/linter/linter.ts
  src/components/editor-page/editor-pane/linter/single-line-regex-linter.spec.ts
  src/components/editor-page/editor-pane/linter/single-line-regex-linter.ts
  src/components/editor-page/renderer-pane/yaml-array-deprecation-alert.tsx
  src/components/markdown-renderer/invalid-yaml-alert.tsx
  src/components/markdown-renderer/markdown-extension/legacy-short-codes/legacy-shortcodes-markdown-extension.ts
  src/components/markdown-renderer/markdown-extension/legacy-short-codes/replace-legacy-pdf-short-code.ts
  src/components/markdown-renderer/markdown-extension/legacy-short-codes/replace-legacy-slideshare-short-code.ts
  src/components/markdown-renderer/markdown-extension/legacy-short-codes/replace-legacy-speakerdeck-short-code.ts
  src/components/markdown-renderer/markdown-extension/markdown-extension.ts
  src/components/markdown-renderer/markdown-extension/sequence-diagram/deprecation-warning.tsx
  src/components/markdown-renderer/markdown-extension/sequence-diagram/sequence-diagram-markdown-extension.ts
  src/components/markdown-renderer/markdown-extension/sequence-diagram/sequence-diagram.tsx
  src/components/markdown-renderer/markdown-extension/vimeo/replace-legacy-vimeo-short-code.ts
  src/components/markdown-renderer/markdown-extension/vimeo/vimeo-markdown-extension.ts
  src/components/markdown-renderer/markdown-extension/youtube/replace-legacy-youtube-short-code.ts
  src/components/markdown-renderer/markdown-extension/youtube/youtube-markdown-extension.ts
  src/components/render-page/markdown-document.tsx
  src/redux/note-details/build-state-from-updated-markdown-content.ts
  src/redux/note-details/initial-state.ts
  src/redux/note-details/raw-note-frontmatter-parser/parser.test.ts
  src/redux/note-details/raw-note-frontmatter-parser/parser.ts
  src/redux/note-details/raw-note-frontmatter-parser/types.d.ts
  src/redux/note-details/reducers/build-state-from-set-note-data-from-server.test.ts
  src/redux/note-details/types/note-details.ts
  yarn.lock
Labels: type: feature, scope: editor, status: ready to merge
