Repository hedgedoc/react-client, pull requests merged in 2022-02, with the labels that each got.

#1836 Replace "cypress-file-upload" with cypress selectFile
  cypress/integration/fileUpload.spec.ts
  cypress/integration/history.spec.ts
  cypress/integration/import.spec.ts
  cypress/support/index.ts
  package.json
  yarn.lock
Labels: type: maintenance

#1837 Add main netlify deployment on GH actions
  .github/workflows/deploy-main.yml
  .github/workflows/deploy-pr.yml
  netlify/deploy-main.sh
  netlify/deploy-pr.sh
Labels: type: ci/cd

#1838 Add commit hash to version on netlify deployment
  netlify.toml
  netlify/build.sh
  netlify/patch-files.sh
  netlify/patch-intro.js
  package.json
Labels: type: code quality enhancement, type: maintenance

#1840 Add markdown renderer for motd
  CHANGELOG.md
  cypress/integration/motd.spec.ts
  cypress/support/config.ts
  netlify/intro.md
  netlify/intro.md.license
  netlify/motd.md
  netlify/motd.md.license
  netlify/motd.txt
  netlify/patch-files.sh
  public/mock-backend/public/motd.md
  src/components/application-loader/initializers/fetch-motd.ts
  src/components/common/motd-modal/motd-modal.tsx
  src/components/common/motd-modal/motd-renderer.tsx
  src/components/markdown-renderer/hooks/use-convert-markdown-to-react-dom.ts
  src/components/markdown-renderer/replace-components/component-replacer.ts
Labels: type: feature enhancement

#1856 Fix renovate match string for docker images
  renovate.json
Labels: type: bug, type: maintenance

#1734 refactor: Deduplicate delete modal
  src/components/editor-page/sidebar/delete-note-sidebar-entry/delete-note-modal.tsx
  src/components/history-page/entry-menu/delete-note-item.tsx
  src/components/history-page/entry-menu/dropdown-item-with-deletion-modal.tsx
  src/components/history-page/history-card/history-card.tsx
Labels: type: code quality enhancement

#1861 Fix smooth scroll and other bugs
  src/components/editor-page/editor-page-content.tsx
  src/components/editor-page/editor-pane/editor-pane.tsx
  src/components/editor-page/editor-pane/hooks/use-cursor-activity-callback.ts
  src/components/editor-page/editor-pane/tool-bar/emoji-picker/emoji-picker-button.tsx
  src/components/editor-page/editor-pane/tool-bar/tool-bar.tsx
  src/components/editor-page/render-context/editor-to-renderer-communicator-context-provider.tsx
  src/components/editor-page/render-context/renderer-to-editor-communicator-context-provider.tsx
  src/components/editor-page/renderer-pane/render-iframe.tsx
  src/components/markdown-renderer/markdown-extension/link-replacer/jump-anchor.tsx
  src/components/render-page/hooks/sync-scroll/use-document-sync-scrolling.ts
  src/components/render-page/hooks/sync-scroll/use-on-user-scroll.ts
  src/components/render-page/markdown-document.tsx
  src/components/render-page/window-post-message-communicator/hooks/use-send-to-renderer.ts
  src/components/render-page/window-post-message-communicator/window-post-message-communicator.ts
  src/pages/n/[id].tsx
Labels: type: bug

#1885 Add missing parameter for deployment action
  .github/workflows/deploy-main.yml
  .github/workflows/deploy-pr.yml
Labels: type: bug, type: maintenance
